import type { Document } from "@apzhub/legal-business-core";

import { SEED_MATTERS } from "../matters/seed-matters";
import { SEED_FOLDERS } from "./seed-folders";

function matter(index: number) {
  return SEED_MATTERS[index]!;
}

function folder(index: number) {
  return SEED_FOLDERS[index]!;
}

/** Twenty realistic seed documents linked to matters (LAW-004-01). */
export const SEED_DOCUMENTS: readonly Document[] = [
  {
    documentId: "d1000001-0001-4000-8000-000000000001",
    documentReference: "DOC-2026-00001",
    title: "Statement of Claim — Harbourview Zoning Appeal",
    documentType: "pleading",
    documentStatus: "filed",
    documentCategoryId: "pleadings",
    matterId: matter(0).matterId,
    clientId: matter(0).clientId,
    folderId: folder(0).folderId,
    version: 2,
    fileName: "statement-of-claim-harbourview.pdf",
    mimeType: "application/pdf",
    sizeBytes: 245_760,
    createdByUserId: "user-legal-workbench",
    tags: ["pleading", "filed"],
    customFields: { court: "Land and Environment Court" },
  },
  {
    documentId: "d1000001-0001-4000-8000-000000000002",
    documentReference: "DOC-2026-00002",
    title: "Council Correspondence Pack",
    documentType: "correspondence",
    documentStatus: "approved",
    documentCategoryId: "correspondence",
    matterId: matter(0).matterId,
    clientId: matter(0).clientId,
    folderId: folder(1).folderId,
    version: 1,
    fileName: "council-correspondence-pack.pdf",
    mimeType: "application/pdf",
    sizeBytes: 512_000,
    createdByUserId: "user-legal-workbench",
    tags: ["correspondence"],
    customFields: {},
  },
  {
    documentId: "d1000001-0001-4000-8000-000000000003",
    documentReference: "DOC-2026-00003",
    title: "Affidavit — Elena Vasquez",
    documentType: "evidence",
    documentStatus: "review",
    documentCategoryId: "evidence",
    matterId: matter(1).matterId,
    clientId: matter(1).clientId,
    folderId: folder(4).folderId,
    version: 1,
    fileName: "affidavit-vasquez.pdf",
    mimeType: "application/pdf",
    sizeBytes: 180_224,
    createdByUserId: "user-legal-workbench",
    tags: ["affidavit", "family"],
    customFields: {},
  },
  {
    documentId: "d1000001-0001-4000-8000-000000000004",
    documentReference: "DOC-2026-00004",
    title: "Parenting Plan Draft",
    documentType: "contract",
    documentStatus: "draft",
    documentCategoryId: "contracts",
    matterId: matter(1).matterId,
    clientId: matter(1).clientId,
    version: 1,
    fileName: "parenting-plan-draft.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    sizeBytes: 98_304,
    createdByUserId: "user-legal-workbench",
    tags: ["parenting"],
    customFields: {},
  },
  {
    documentId: "d1000001-0001-4000-8000-000000000005",
    documentReference: "DOC-2026-00005",
    title: "EPA Compliance Checklist",
    documentType: "research",
    documentStatus: "approved",
    documentCategoryId: "research",
    matterId: matter(2).matterId,
    clientId: matter(2).clientId,
    version: 1,
    fileName: "epa-compliance-checklist.pdf",
    mimeType: "application/pdf",
    sizeBytes: 156_672,
    createdByUserId: "user-legal-workbench",
    tags: ["regulatory"],
    customFields: { regulator: "EPA NSW" },
  },
  {
    documentId: "d1000001-0001-4000-8000-000000000006",
    documentReference: "DOC-2026-00006",
    title: "Series B Share Subscription Agreement",
    documentType: "contract",
    documentStatus: "approved",
    documentCategoryId: "contracts",
    matterId: matter(4).matterId,
    clientId: matter(4).clientId,
    folderId: folder(2).folderId,
    version: 3,
    fileName: "series-b-subscription-agreement.pdf",
    mimeType: "application/pdf",
    sizeBytes: 892_928,
    createdByUserId: "user-legal-workbench",
    tags: ["M&A", "equity"],
    customFields: {},
  },
  {
    documentId: "d1000001-0001-4000-8000-000000000007",
    documentReference: "DOC-2026-00007",
    title: "Due Diligence Memo",
    documentType: "research",
    documentStatus: "review",
    documentCategoryId: "research",
    matterId: matter(4).matterId,
    clientId: matter(4).clientId,
    folderId: folder(2).folderId,
    version: 1,
    fileName: "due-diligence-memo.pdf",
    mimeType: "application/pdf",
    sizeBytes: 421_888,
    createdByUserId: "user-legal-workbench",
    tags: ["due-diligence"],
    customFields: {},
  },
  {
    documentId: "d1000001-0001-4000-8000-000000000008",
    documentReference: "DOC-2026-00008",
    title: "Trust Deed Amendment",
    documentType: "contract",
    documentStatus: "filed",
    documentCategoryId: "contracts",
    matterId: matter(8).matterId,
    clientId: matter(8).clientId,
    version: 2,
    fileName: "trust-deed-amendment.pdf",
    mimeType: "application/pdf",
    sizeBytes: 334_848,
    createdByUserId: "user-legal-workbench",
    tags: ["trust"],
    customFields: {},
  },
  {
    documentId: "d1000001-0001-4000-8000-000000000009",
    documentReference: "DOC-2026-00009",
    title: "Beneficiary Correspondence Log",
    documentType: "correspondence",
    documentStatus: "approved",
    documentCategoryId: "correspondence",
    matterId: matter(8).matterId,
    clientId: matter(8).clientId,
    folderId: folder(3).folderId,
    version: 1,
    fileName: "beneficiary-correspondence-log.pdf",
    mimeType: "application/pdf",
    sizeBytes: 204_800,
    createdByUserId: "user-legal-workbench",
    tags: ["beneficiary"],
    customFields: {},
  },
  {
    documentId: "d1000001-0001-4000-8000-000000000010",
    documentReference: "DOC-2026-00010",
    title: "Solar Farm Acquisition Term Sheet",
    documentType: "contract",
    documentStatus: "draft",
    documentCategoryId: "contracts",
    matterId: matter(9).matterId,
    clientId: matter(9).clientId,
    version: 1,
    fileName: "solar-farm-term-sheet.pdf",
    mimeType: "application/pdf",
    sizeBytes: 145_408,
    createdByUserId: "user-legal-workbench",
    tags: ["acquisition"],
    customFields: {},
  },
  {
    documentId: "d1000001-0001-4000-8000-000000000011",
    documentReference: "DOC-2026-00011",
    title: "IP Licensing Schedule",
    documentType: "contract",
    documentStatus: "review",
    documentCategoryId: "contracts",
    matterId: matter(10).matterId,
    clientId: matter(10).clientId,
    version: 1,
    fileName: "ip-licensing-schedule.pdf",
    mimeType: "application/pdf",
    sizeBytes: 267_264,
    createdByUserId: "user-legal-workbench",
    tags: ["IP"],
    customFields: {},
  },
  {
    documentId: "d1000001-0001-4000-8000-000000000012",
    documentReference: "DOC-2026-00012",
    title: "Lease Heads of Agreement",
    documentType: "contract",
    documentStatus: "approved",
    documentCategoryId: "contracts",
    matterId: matter(11).matterId,
    clientId: matter(11).clientId,
    version: 2,
    fileName: "lease-heads-of-agreement.pdf",
    mimeType: "application/pdf",
    sizeBytes: 198_656,
    createdByUserId: "user-legal-workbench",
    tags: ["lease"],
    customFields: {},
  },
  {
    documentId: "d1000001-0001-4000-8000-000000000013",
    documentReference: "DOC-2026-00013",
    title: "Estate Planning Questionnaire",
    documentType: "correspondence",
    documentStatus: "draft",
    documentCategoryId: "correspondence",
    matterId: matter(12).matterId,
    clientId: matter(12).clientId,
    version: 1,
    fileName: "estate-planning-questionnaire.pdf",
    mimeType: "application/pdf",
    sizeBytes: 122_880,
    createdByUserId: "user-legal-workbench",
    tags: ["estate"],
    customFields: {},
  },
  {
    documentId: "d1000001-0001-4000-8000-000000000014",
    documentReference: "DOC-2026-00014",
    title: "Judicial Review Application",
    documentType: "pleading",
    documentStatus: "filed",
    documentCategoryId: "pleadings",
    matterId: matter(13).matterId,
    clientId: matter(13).clientId,
    version: 1,
    fileName: "judicial-review-application.pdf",
    mimeType: "application/pdf",
    sizeBytes: 389_120,
    createdByUserId: "user-legal-workbench",
    tags: ["judicial review"],
    customFields: {},
  },
  {
    documentId: "d1000001-0001-4000-8000-000000000015",
    documentReference: "DOC-2026-00015",
    title: "ASIC Regulatory Submission Draft",
    documentType: "correspondence",
    documentStatus: "review",
    documentCategoryId: "correspondence",
    matterId: matter(14).matterId,
    clientId: matter(14).clientId,
    version: 1,
    fileName: "asic-regulatory-submission.pdf",
    mimeType: "application/pdf",
    sizeBytes: 456_704,
    createdByUserId: "user-legal-workbench",
    tags: ["ASIC"],
    customFields: {},
  },
  {
    documentId: "d1000001-0001-4000-8000-000000000016",
    documentReference: "DOC-2026-00016",
    title: "Development Consent Advice",
    documentType: "research",
    documentStatus: "approved",
    documentCategoryId: "research",
    matterId: matter(15).matterId,
    clientId: matter(15).clientId,
    version: 1,
    fileName: "development-consent-advice.pdf",
    mimeType: "application/pdf",
    sizeBytes: 278_528,
    createdByUserId: "user-legal-workbench",
    tags: ["planning"],
    customFields: {},
  },
  {
    documentId: "d1000001-0001-4000-8000-000000000017",
    documentReference: "DOC-2026-00017",
    title: "Defamation Defence Outline",
    documentType: "pleading",
    documentStatus: "draft",
    documentCategoryId: "pleadings",
    matterId: matter(16).matterId,
    clientId: matter(16).clientId,
    version: 1,
    fileName: "defamation-defence-outline.pdf",
    mimeType: "application/pdf",
    sizeBytes: 167_936,
    createdByUserId: "user-legal-workbench",
    tags: ["defamation"],
    customFields: {},
  },
  {
    documentId: "d1000001-0001-4000-8000-000000000018",
    documentReference: "DOC-2026-00018",
    title: "Privacy Breach Notification Template",
    documentType: "correspondence",
    documentStatus: "approved",
    documentCategoryId: "correspondence",
    matterId: matter(17).matterId,
    clientId: matter(17).clientId,
    version: 1,
    fileName: "privacy-breach-notification.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    sizeBytes: 87_040,
    createdByUserId: "user-legal-workbench",
    tags: ["privacy"],
    customFields: {},
  },
  {
    documentId: "d1000001-0001-4000-8000-000000000019",
    documentReference: "DOC-2026-00019",
    title: "Construction Delay Expert Report",
    documentType: "evidence",
    documentStatus: "review",
    documentCategoryId: "evidence",
    matterId: matter(18).matterId,
    clientId: matter(18).clientId,
    version: 1,
    fileName: "construction-delay-expert-report.pdf",
    mimeType: "application/pdf",
    sizeBytes: 1_048_576,
    createdByUserId: "user-legal-workbench",
    tags: ["expert", "construction"],
    customFields: {},
  },
  {
    documentId: "d1000001-0001-4000-8000-000000000020",
    documentReference: "DOC-2026-00020",
    title: "Trade Compliance Checklist",
    documentType: "research",
    documentStatus: "draft",
    documentCategoryId: "research",
    matterId: matter(19).matterId,
    clientId: matter(19).clientId,
    version: 1,
    fileName: "trade-compliance-checklist.pdf",
    mimeType: "application/pdf",
    sizeBytes: 131_072,
    createdByUserId: "user-legal-workbench",
    tags: ["trade"],
    customFields: {},
  },
];
