import { permissionPatternMatches } from "@apzhub/platform-authorization";

import { unauthorizedError } from "../errors";
import type { AggregateKind, RepositoryContext } from "../types";

export type RepositoryOperation =
  "list" | "get" | "search" | "create" | "update" | "archive" | "restore" | "append";

/**
 * Maps repository operations to specific permission keys (OR semantics).
 * Granted namespace wildcards (testing.*, evidence.*, …) and global `*` match via
 * permissionPatternMatches — never short-circuit with allow-all.
 */
export const OPERATION_PERMISSION_MAP: Readonly<
  Record<AggregateKind, Readonly<Record<RepositoryOperation, readonly string[]>>>
> = {
  requirement: {
    list: ["testing.requirements.list", "testing.view", "testing.admin"],
    get: ["testing.requirements.read", "testing.view", "testing.admin"],
    search: ["testing.requirements.list", "testing.view", "testing.admin"],
    create: ["testing.requirements.create", "testing.admin"],
    update: ["testing.requirements.update", "testing.admin"],
    archive: ["testing.requirements.update", "testing.admin"],
    restore: ["testing.requirements.update", "testing.admin"],
    append: ["testing.requirements.update", "testing.admin"],
  },
  work_item: {
    list: ["testing.requirements.list", "testing.view", "testing.admin"],
    get: ["testing.requirements.read", "testing.view", "testing.admin"],
    search: ["testing.requirements.list", "testing.view", "testing.admin"],
    create: ["testing.requirements.create", "testing.admin"],
    update: ["testing.requirements.update", "testing.admin"],
    archive: ["testing.requirements.update", "testing.admin"],
    restore: ["testing.requirements.update", "testing.admin"],
    append: ["testing.requirements.update", "testing.admin"],
  },
  risk: {
    list: ["testing.requirements.list", "testing.view", "testing.admin"],
    get: ["testing.requirements.read", "testing.view", "testing.admin"],
    search: ["testing.requirements.list", "testing.view", "testing.admin"],
    create: ["testing.requirements.create", "testing.admin"],
    update: ["testing.requirements.update", "testing.admin"],
    archive: ["testing.requirements.update", "testing.admin"],
    restore: ["testing.requirements.update", "testing.admin"],
    append: ["testing.requirements.update", "testing.admin"],
  },
  test_plan: {
    list: ["testing.plans.list", "testing.view", "testing.admin"],
    get: ["testing.plans.read", "testing.view", "testing.admin"],
    search: ["testing.plans.list", "testing.view", "testing.admin"],
    create: ["testing.plans.create", "testing.admin"],
    update: ["testing.plans.update", "testing.admin"],
    archive: ["testing.plans.update", "testing.admin"],
    restore: ["testing.plans.update", "testing.admin"],
    append: ["testing.plans.update", "testing.admin"],
  },
  test_suite: {
    list: ["testing.suites.list", "testing.view", "testing.admin"],
    get: ["testing.suites.read", "testing.view", "testing.admin"],
    search: ["testing.suites.list", "testing.view", "testing.admin"],
    create: ["testing.suites.create", "testing.admin"],
    update: ["testing.suites.update", "testing.admin"],
    archive: ["testing.suites.update", "testing.admin"],
    restore: ["testing.suites.update", "testing.admin"],
    append: ["testing.suites.update", "testing.admin"],
  },
  test_case: {
    list: ["testing.cases.list", "testing.view", "testing.admin"],
    get: ["testing.cases.read", "testing.view", "testing.admin"],
    search: ["testing.cases.list", "testing.view", "testing.admin"],
    create: ["testing.cases.create", "testing.admin"],
    update: ["testing.cases.update", "testing.admin"],
    archive: ["testing.cases.update", "testing.admin"],
    restore: ["testing.cases.update", "testing.admin"],
    append: ["testing.cases.update", "testing.admin"],
  },
  test_step: {
    list: ["testing.cases.list", "testing.view", "testing.admin"],
    get: ["testing.cases.read", "testing.view", "testing.admin"],
    search: ["testing.cases.list", "testing.view", "testing.admin"],
    create: ["testing.cases.create", "testing.admin"],
    update: ["testing.cases.update", "testing.admin"],
    archive: ["testing.cases.update", "testing.admin"],
    restore: ["testing.cases.update", "testing.admin"],
    append: ["testing.cases.update", "testing.admin"],
  },
  test_case_version: {
    list: ["testing.cases.list", "testing.view", "testing.admin"],
    get: ["testing.cases.read", "testing.view", "testing.admin"],
    search: ["testing.cases.list", "testing.view", "testing.admin"],
    create: ["testing.cases.update", "testing.cases.create", "testing.admin"],
    update: ["testing.cases.update", "testing.admin"],
    archive: ["testing.cases.update", "testing.admin"],
    restore: ["testing.cases.update", "testing.admin"],
    append: ["testing.cases.update", "testing.admin"],
  },
  test_plan_version: {
    list: ["testing.plans.list", "testing.view", "testing.admin"],
    get: ["testing.plans.read", "testing.view", "testing.admin"],
    search: ["testing.plans.list", "testing.view", "testing.admin"],
    create: ["testing.plans.update", "testing.plans.create", "testing.admin"],
    update: ["testing.plans.update", "testing.admin"],
    archive: ["testing.plans.update", "testing.admin"],
    restore: ["testing.plans.update", "testing.admin"],
    append: ["testing.plans.update", "testing.admin"],
  },
  test_suite_version: {
    list: ["testing.suites.list", "testing.view", "testing.admin"],
    get: ["testing.suites.read", "testing.view", "testing.admin"],
    search: ["testing.suites.list", "testing.view", "testing.admin"],
    create: ["testing.suites.update", "testing.suites.create", "testing.admin"],
    update: ["testing.suites.update", "testing.admin"],
    archive: ["testing.suites.update", "testing.admin"],
    restore: ["testing.suites.update", "testing.admin"],
    append: ["testing.suites.update", "testing.admin"],
  },
  regression_set: {
    list: ["testing.suites.list", "testing.view", "testing.admin"],
    get: ["testing.suites.read", "testing.view", "testing.admin"],
    search: ["testing.suites.list", "testing.view", "testing.admin"],
    create: ["testing.suites.create", "testing.admin"],
    update: ["testing.suites.update", "testing.admin"],
    archive: ["testing.suites.update", "testing.admin"],
    restore: ["testing.suites.update", "testing.admin"],
    append: ["testing.suites.update", "testing.admin"],
  },
  execution_session: {
    list: ["testing.executions.list", "testing.view", "testing.admin"],
    get: ["testing.executions.read", "testing.view", "testing.admin"],
    search: ["testing.executions.list", "testing.view", "testing.admin"],
    create: ["testing.executions.create", "testing.admin"],
    update: [
      "testing.executions.execute",
      "testing.executions.create",
      "testing.admin",
    ],
    archive: ["testing.executions.execute", "testing.admin"],
    restore: ["testing.executions.execute", "testing.admin"],
    append: ["testing.executions.execute", "testing.admin"],
  },
  execution_history: {
    list: ["testing.executions.list", "testing.view", "testing.admin"],
    get: ["testing.executions.read", "testing.view", "testing.admin"],
    search: ["testing.executions.list", "testing.view", "testing.admin"],
    create: [
      "testing.executions.execute",
      "testing.executions.create",
      "testing.admin",
    ],
    update: ["testing.executions.execute", "testing.admin"],
    archive: ["testing.executions.execute", "testing.admin"],
    restore: ["testing.executions.execute", "testing.admin"],
    append: [
      "testing.executions.execute",
      "testing.executions.create",
      "testing.admin",
    ],
  },
  manual_execution: {
    list: ["testing.executions.list", "testing.view", "testing.admin"],
    get: ["testing.executions.read", "testing.view", "testing.admin"],
    search: ["testing.executions.list", "testing.view", "testing.admin"],
    create: [
      "testing.executions.execute",
      "testing.executions.create",
      "testing.admin",
    ],
    update: [
      "testing.executions.execute",
      "testing.executions.create",
      "testing.admin",
    ],
    archive: ["testing.executions.execute", "testing.admin"],
    restore: ["testing.executions.execute", "testing.admin"],
    append: ["testing.executions.execute", "testing.admin"],
  },
  manual_step_actual: {
    list: ["testing.executions.list", "testing.view", "testing.admin"],
    get: ["testing.executions.read", "testing.view", "testing.admin"],
    search: ["testing.executions.list", "testing.view", "testing.admin"],
    create: ["testing.executions.execute", "testing.admin"],
    update: ["testing.executions.execute", "testing.admin"],
    archive: ["testing.executions.execute", "testing.admin"],
    restore: ["testing.executions.execute", "testing.admin"],
    append: ["testing.executions.execute", "testing.admin"],
  },
  evidence: {
    list: ["evidence.list", "evidence.admin"],
    get: ["evidence.read", "evidence.admin"],
    search: ["evidence.list", "evidence.admin"],
    create: ["evidence.register", "evidence.admin"],
    update: ["evidence.register", "evidence.admin"],
    archive: ["evidence.admin"],
    restore: ["evidence.admin"],
    append: ["evidence.register", "evidence.admin"],
  },
  approval: {
    list: ["approval.list", "approval.admin"],
    get: ["approval.read", "approval.admin"],
    search: ["approval.list", "approval.admin"],
    create: ["approval.request", "approval.admin"],
    update: ["approval.decide", "approval.sign", "approval.admin"],
    archive: ["approval.admin"],
    restore: ["approval.admin"],
    append: ["approval.request", "approval.admin"],
  },
  approval_history: {
    list: ["approval.list", "approval.admin"],
    get: ["approval.read", "approval.admin"],
    search: ["approval.list", "approval.admin"],
    create: ["approval.request", "approval.decide", "approval.admin"],
    update: ["approval.admin"],
    archive: ["approval.admin"],
    restore: ["approval.admin"],
    append: ["approval.request", "approval.decide", "approval.admin"],
  },
  certification_record: {
    list: [
      "certification.records.list",
      "certification.view",
      "certification.create",
      "certification.admin",
    ],
    get: ["certification.records.read", "certification.view", "certification.admin"],
    search: ["certification.records.list", "certification.view", "certification.admin"],
    create: [
      "certification.records.create",
      "certification.create",
      "certification.admin",
    ],
    update: [
      "certification.records.transition",
      "certification.review",
      "certification.approve",
      "certification.reject",
      "certification.override",
      "certification.gates.evaluate",
      "certification.admin",
    ],
    archive: ["certification.admin", "certification.override"],
    restore: ["certification.admin", "certification.override"],
    append: [
      "certification.records.create",
      "certification.create",
      "certification.admin",
    ],
  },
  certification_gate_definition: {
    list: ["certification.view", "certification.gates.evaluate", "certification.admin"],
    get: ["certification.view", "certification.gates.evaluate", "certification.admin"],
    search: [
      "certification.view",
      "certification.gates.evaluate",
      "certification.admin",
    ],
    create: ["certification.admin"],
    update: ["certification.admin"],
    archive: ["certification.admin"],
    restore: ["certification.admin"],
    append: ["certification.admin"],
  },
  certification_gate_evaluation: {
    list: ["certification.view", "certification.gates.evaluate", "certification.admin"],
    get: ["certification.view", "certification.gates.evaluate", "certification.admin"],
    search: [
      "certification.view",
      "certification.gates.evaluate",
      "certification.admin",
    ],
    create: ["certification.gates.evaluate", "certification.admin"],
    update: ["certification.gates.evaluate", "certification.admin"],
    archive: ["certification.admin"],
    restore: ["certification.admin"],
    append: ["certification.gates.evaluate", "certification.admin"],
  },
  certification_rule: {
    list: ["certification.view", "certification.admin"],
    get: ["certification.view", "certification.admin"],
    search: ["certification.view", "certification.admin"],
    create: ["certification.admin"],
    update: ["certification.admin"],
    archive: ["certification.admin"],
    restore: ["certification.admin"],
    append: ["certification.admin"],
  },
  certification_audit: {
    list: ["certification.audit", "certification.view", "certification.admin"],
    get: ["certification.audit", "certification.view", "certification.admin"],
    search: ["certification.audit", "certification.view", "certification.admin"],
    create: ["certification.audit", "certification.admin"],
    update: ["certification.admin"],
    archive: ["certification.admin"],
    restore: ["certification.admin"],
    append: [
      "certification.audit",
      "certification.create",
      "certification.records.create",
      "certification.records.transition",
      "certification.review",
      "certification.approve",
      "certification.reject",
      "certification.override",
      "certification.gates.evaluate",
      "certification.admin",
    ],
  },
  certification_history: {
    list: ["certification.view", "certification.audit", "certification.admin"],
    get: ["certification.view", "certification.audit", "certification.admin"],
    search: ["certification.view", "certification.audit", "certification.admin"],
    create: [
      "certification.records.transition",
      "certification.create",
      "certification.admin",
    ],
    update: ["certification.admin"],
    archive: ["certification.admin"],
    restore: ["certification.admin"],
    append: [
      "certification.records.transition",
      "certification.create",
      "certification.records.create",
      "certification.review",
      "certification.approve",
      "certification.reject",
      "certification.override",
      "certification.admin",
    ],
  },
  release_readiness: {
    list: [
      "release.view",
      "certification.records.list",
      "certification.view",
      "release.admin",
      "certification.admin",
    ],
    get: [
      "release.view",
      "certification.records.read",
      "certification.view",
      "release.admin",
      "certification.admin",
    ],
    search: [
      "release.view",
      "certification.records.list",
      "certification.view",
      "release.admin",
      "certification.admin",
    ],
    create: [
      "release.compute",
      "certification.gates.evaluate",
      "release.admin",
      "certification.admin",
    ],
    update: [
      "release.compute",
      "certification.gates.evaluate",
      "release.admin",
      "certification.admin",
    ],
    archive: ["release.admin", "certification.admin"],
    restore: ["release.admin", "certification.admin"],
    append: [
      "release.compute",
      "certification.gates.evaluate",
      "release.admin",
      "certification.admin",
    ],
  },
  release: {
    list: ["release.view", "release.admin"],
    get: ["release.view", "release.admin"],
    search: ["release.view", "release.admin"],
    create: ["release.create", "release.admin"],
    update: [
      "release.update",
      "release.submit",
      "release.approve",
      "release.reject",
      "release.withdraw",
      "release.admin",
    ],
    archive: ["release.archive", "release.admin"],
    restore: ["release.restore", "release.admin"],
    append: ["release.create", "release.update", "release.admin"],
  },
  release_scope: {
    list: ["release.view", "release.admin"],
    get: ["release.view", "release.admin"],
    search: ["release.view", "release.admin"],
    create: ["release.update", "release.admin"],
    update: ["release.update", "release.admin"],
    archive: ["release.update", "release.admin"],
    restore: ["release.update", "release.admin"],
    append: ["release.update", "release.admin"],
  },
  release_package: {
    list: ["release.view", "release.admin"],
    get: ["release.view", "release.admin"],
    search: ["release.view", "release.admin"],
    create: ["release.update", "release.admin"],
    update: ["release.update", "release.admin"],
    archive: ["release.update", "release.admin"],
    restore: ["release.update", "release.admin"],
    append: ["release.update", "release.admin"],
  },
  release_candidate: {
    list: ["release.view", "release.admin"],
    get: ["release.view", "release.admin"],
    search: ["release.view", "release.admin"],
    create: ["release.update", "release.admin"],
    update: ["release.update", "release.admin"],
    archive: ["release.update", "release.admin"],
    restore: ["release.update", "release.admin"],
    append: ["release.update", "release.admin"],
  },
  release_approval: {
    list: ["release.approvals.view", "release.approvals.admin"],
    get: ["release.approvals.view", "release.approvals.admin"],
    search: ["release.approvals.view", "release.approvals.admin"],
    create: ["release.approvals.request", "release.approvals.admin"],
    update: [
      "release.approvals.request",
      "release.approvals.decide",
      "release.approvals.admin",
    ],
    archive: ["release.approvals.admin"],
    restore: ["release.approvals.admin"],
    append: ["release.approvals.request", "release.approvals.admin"],
  },
  release_decision: {
    list: ["release.view", "release.approve", "release.reject", "release.admin"],
    get: ["release.view", "release.approve", "release.reject", "release.admin"],
    search: ["release.view", "release.approve", "release.reject", "release.admin"],
    create: ["release.approve", "release.reject", "release.admin"],
    update: ["release.admin"],
    archive: ["release.admin"],
    restore: ["release.admin"],
    append: ["release.approve", "release.reject", "release.admin"],
  },
  release_evidence: {
    list: ["release.view", "release.admin"],
    get: ["release.view", "release.admin"],
    search: ["release.view", "release.admin"],
    create: ["release.update", "release.admin"],
    update: ["release.update", "release.admin"],
    archive: ["release.update", "release.admin"],
    restore: ["release.update", "release.admin"],
    append: ["release.update", "release.admin"],
  },
  release_dependency: {
    list: ["release.view", "release.admin"],
    get: ["release.view", "release.admin"],
    search: ["release.view", "release.admin"],
    create: ["release.update", "release.admin"],
    update: ["release.update", "release.admin"],
    archive: ["release.update", "release.admin"],
    restore: ["release.update", "release.admin"],
    append: ["release.update", "release.admin"],
  },
  release_note: {
    list: ["release.view", "release.admin"],
    get: ["release.view", "release.admin"],
    search: ["release.view", "release.admin"],
    create: ["release.update", "release.admin"],
    update: ["release.update", "release.admin"],
    archive: ["release.update", "release.admin"],
    restore: ["release.update", "release.admin"],
    append: ["release.update", "release.admin"],
  },
  release_risk_assessment: {
    list: ["release.risk.view", "release.risk.admin"],
    get: ["release.risk.view", "release.risk.admin"],
    search: ["release.risk.view", "release.risk.admin"],
    create: ["release.risk.evaluate", "release.risk.admin"],
    update: ["release.risk.evaluate", "release.risk.admin"],
    archive: ["release.risk.admin"],
    restore: ["release.risk.admin"],
    append: ["release.risk.evaluate", "release.risk.admin"],
  },
  release_readiness_snapshot: {
    list: ["release.readiness.view", "release.readiness.admin"],
    get: ["release.readiness.view", "release.readiness.admin"],
    search: ["release.readiness.view", "release.readiness.admin"],
    create: ["release.readiness.evaluate", "release.readiness.admin"],
    update: ["release.readiness.evaluate", "release.readiness.admin"],
    archive: ["release.readiness.admin"],
    restore: ["release.readiness.admin"],
    append: ["release.readiness.evaluate", "release.readiness.admin"],
  },
  release_summary_snapshot: {
    list: ["release.readiness.view", "release.readiness.admin"],
    get: ["release.readiness.view", "release.readiness.admin"],
    search: ["release.readiness.view", "release.readiness.admin"],
    create: ["release.readiness.evaluate", "release.readiness.admin"],
    update: ["release.readiness.evaluate", "release.readiness.admin"],
    archive: ["release.readiness.admin"],
    restore: ["release.readiness.admin"],
    append: ["release.readiness.evaluate", "release.readiness.admin"],
  },
  release_audit_entry: {
    list: ["release.audit.view", "release.audit.admin"],
    get: ["release.audit.view", "release.audit.admin"],
    search: ["release.audit.view", "release.audit.admin"],
    create: ["release.audit.admin"],
    update: ["release.audit.admin"],
    archive: ["release.audit.admin"],
    restore: ["release.audit.admin"],
    append: [
      "release.audit.admin",
      "release.create",
      "release.update",
      "release.submit",
      "release.approve",
      "release.reject",
      "release.withdraw",
      "release.archive",
      "release.restore",
      "release.approvals.request",
      "release.approvals.decide",
      "release.risk.evaluate",
      "release.readiness.evaluate",
      "release.admin",
    ],
  },
  coverage_record: {
    list: ["coverage.view", "reporting.view", "coverage.admin", "reporting.admin"],
    get: ["coverage.view", "reporting.view", "coverage.admin", "reporting.admin"],
    search: ["coverage.view", "reporting.view", "coverage.admin", "reporting.admin"],
    create: [
      "coverage.compute",
      "reporting.generate",
      "coverage.admin",
      "reporting.admin",
    ],
    update: [
      "coverage.compute",
      "reporting.generate",
      "coverage.admin",
      "reporting.admin",
    ],
    archive: ["coverage.admin", "reporting.admin"],
    restore: ["coverage.admin", "reporting.admin"],
    append: [
      "coverage.compute",
      "reporting.generate",
      "coverage.admin",
      "reporting.admin",
    ],
  },
  defect_link: {
    list: ["defects.view", "defects.admin"],
    get: ["defects.view", "defects.admin"],
    search: ["defects.view", "defects.admin"],
    create: ["defects.link", "defects.admin"],
    update: ["defects.update", "defects.link", "defects.admin"],
    archive: ["defects.admin"],
    restore: ["defects.admin"],
    append: ["defects.link", "defects.admin"],
  },
  quality_snapshot: {
    list: ["quality.view", "quality.admin"],
    get: ["quality.view", "quality.admin"],
    search: ["quality.view", "quality.admin"],
    create: ["quality.compute", "quality.admin"],
    update: ["quality.compute", "quality.admin"],
    archive: ["quality.admin"],
    restore: ["quality.admin"],
    append: ["quality.compute", "quality.admin"],
  },
  regression_analysis: {
    list: ["quality.view", "quality.admin"],
    get: ["quality.view", "quality.admin"],
    search: ["quality.view", "quality.admin"],
    create: ["quality.compute", "quality.admin"],
    update: ["quality.compute", "quality.admin"],
    archive: ["quality.admin"],
    restore: ["quality.admin"],
    append: ["quality.compute", "quality.admin"],
  },
  automation_definition: {
    list: ["automation.jobs.list", "automation.view", "automation.admin"],
    get: ["automation.jobs.read", "automation.view", "automation.admin"],
    search: ["automation.jobs.list", "automation.view", "automation.admin"],
    create: ["automation.jobs.enqueue", "automation.admin"],
    update: ["automation.jobs.enqueue", "automation.admin"],
    archive: ["automation.admin"],
    restore: ["automation.admin"],
    append: ["automation.jobs.enqueue", "automation.admin"],
  },
  automation_import: {
    list: ["automation.view", "automation.import", "automation.admin"],
    get: ["automation.view", "automation.import", "automation.admin"],
    search: ["automation.view", "automation.import", "automation.admin"],
    create: ["automation.import", "automation.admin"],
    update: ["automation.import", "automation.admin"],
    archive: ["automation.admin"],
    restore: ["automation.admin"],
    append: ["automation.import", "automation.admin"],
  },
  automated_execution: {
    list: ["automation.view", "automation.admin"],
    get: ["automation.view", "automation.admin"],
    search: ["automation.view", "automation.admin"],
    create: ["automation.import", "automation.admin"],
    update: ["automation.import", "automation.admin"],
    archive: ["automation.admin"],
    restore: ["automation.admin"],
    append: ["automation.import", "automation.admin"],
  },
  automation_run: {
    list: ["automation.view", "automation.admin"],
    get: ["automation.view", "automation.admin"],
    search: ["automation.view", "automation.admin"],
    create: ["automation.import", "automation.admin"],
    update: ["automation.import", "automation.admin"],
    archive: ["automation.admin"],
    restore: ["automation.admin"],
    append: ["automation.import", "automation.admin"],
  },
  automation_result_item: {
    list: ["automation.view", "automation.admin"],
    get: ["automation.view", "automation.admin"],
    search: ["automation.view", "automation.admin"],
    create: ["automation.import", "automation.admin"],
    update: ["automation.import", "automation.admin"],
    archive: ["automation.admin"],
    restore: ["automation.admin"],
    append: ["automation.import", "automation.admin"],
  },
  automation_import_history: {
    list: ["automation.history", "automation.view", "automation.admin"],
    get: ["automation.history", "automation.view", "automation.admin"],
    search: ["automation.history", "automation.view", "automation.admin"],
    create: ["automation.import", "automation.admin"],
    update: ["automation.admin"],
    archive: ["automation.admin"],
    restore: ["automation.admin"],
    append: ["automation.import", "automation.admin"],
  },
  automation_coverage_snapshot: {
    list: ["automation.coverage", "automation.view", "automation.admin"],
    get: ["automation.coverage", "automation.view", "automation.admin"],
    search: ["automation.coverage", "automation.view", "automation.admin"],
    create: ["automation.import", "automation.coverage", "automation.admin"],
    update: ["automation.coverage", "automation.admin"],
    archive: ["automation.admin"],
    restore: ["automation.admin"],
    append: ["automation.import", "automation.coverage", "automation.admin"],
  },
  pipeline: {
    list: ["pipeline.read", "pipeline.admin"],
    get: ["pipeline.read", "pipeline.admin"],
    search: ["pipeline.read", "pipeline.admin"],
    create: ["pipeline.import", "pipeline.admin"],
    update: ["pipeline.import", "pipeline.admin"],
    archive: ["pipeline.archive", "pipeline.admin"],
    restore: ["pipeline.admin"],
    append: ["pipeline.import", "pipeline.admin"],
  },
  pipeline_import: {
    list: ["pipeline.read", "pipeline.import", "pipeline.admin"],
    get: ["pipeline.read", "pipeline.import", "pipeline.admin"],
    search: ["pipeline.read", "pipeline.import", "pipeline.admin"],
    create: ["pipeline.import", "pipeline.admin"],
    update: ["pipeline.import", "pipeline.admin"],
    archive: ["pipeline.admin"],
    restore: ["pipeline.admin"],
    append: ["pipeline.import", "pipeline.admin"],
  },
  pipeline_run: {
    list: ["pipeline.read", "pipeline.admin"],
    get: ["pipeline.read", "pipeline.admin"],
    search: ["pipeline.read", "pipeline.admin"],
    create: ["pipeline.import", "pipeline.admin"],
    update: ["pipeline.import", "pipeline.link", "pipeline.admin"],
    archive: ["pipeline.admin"],
    restore: ["pipeline.admin"],
    append: ["pipeline.import", "pipeline.admin"],
  },
  pipeline_import_history: {
    list: ["pipeline.audit", "pipeline.read", "pipeline.admin"],
    get: ["pipeline.audit", "pipeline.read", "pipeline.admin"],
    search: ["pipeline.audit", "pipeline.read", "pipeline.admin"],
    create: ["pipeline.import", "pipeline.admin"],
    update: ["pipeline.admin"],
    archive: ["pipeline.admin"],
    restore: ["pipeline.admin"],
    append: ["pipeline.import", "pipeline.admin"],
  },
  engineering_snapshot: {
    list: ["engineering.view", "engineering.admin"],
    get: ["engineering.view", "engineering.admin"],
    search: ["engineering.view", "engineering.admin"],
    create: ["engineering.compute", "engineering.admin"],
    update: ["engineering.compute", "engineering.admin"],
    archive: ["engineering.admin"],
    restore: ["engineering.admin"],
    append: ["engineering.compute", "engineering.admin"],
  },
  engineering_historical_snapshot: {
    list: ["engineering.view", "analytics.view", "engineering.admin"],
    get: ["engineering.view", "analytics.view", "engineering.admin"],
    search: ["engineering.view", "analytics.view", "engineering.admin"],
    create: ["engineering.compute", "engineering.admin"],
    update: ["engineering.compute", "engineering.admin"],
    archive: ["engineering.admin"],
    restore: ["engineering.admin"],
    append: ["engineering.compute", "engineering.admin"],
  },
  engineering_trend_series: {
    list: ["trend.view", "trend.admin"],
    get: ["trend.view", "trend.admin"],
    search: ["trend.view", "trend.admin"],
    create: ["trend.compute", "trend.admin"],
    update: ["trend.compute", "trend.admin"],
    archive: ["trend.admin"],
    restore: ["trend.admin"],
    append: ["trend.compute", "trend.admin"],
  },
  engineering_benchmark: {
    list: ["benchmark.view", "benchmark.admin"],
    get: ["benchmark.view", "benchmark.admin"],
    search: ["benchmark.view", "benchmark.admin"],
    create: ["benchmark.compute", "benchmark.admin"],
    update: ["benchmark.compute", "benchmark.admin"],
    archive: ["benchmark.admin"],
    restore: ["benchmark.admin"],
    append: ["benchmark.compute", "benchmark.admin"],
  },
  engineering_baseline: {
    list: ["benchmark.view", "benchmark.admin"],
    get: ["benchmark.view", "benchmark.admin"],
    search: ["benchmark.view", "benchmark.admin"],
    create: ["benchmark.compute", "benchmark.admin"],
    update: ["benchmark.compute", "benchmark.admin"],
    archive: ["benchmark.admin"],
    restore: ["benchmark.admin"],
    append: ["benchmark.compute", "benchmark.admin"],
  },
  engineering_quality_summary: {
    list: ["quality.view", "quality.score", "analytics.view", "quality.admin"],
    get: ["quality.view", "quality.score", "analytics.view", "quality.admin"],
    search: ["quality.view", "quality.score", "analytics.view", "quality.admin"],
    create: ["quality.score", "quality.admin"],
    update: ["quality.score", "quality.admin"],
    archive: ["quality.admin"],
    restore: ["quality.admin"],
    append: ["quality.score", "quality.admin"],
  },
  report_template: {
    list: ["report.templates", "report.view", "report.admin"],
    get: ["report.templates", "report.view", "report.admin"],
    search: ["report.templates", "report.view", "report.admin"],
    create: ["report.templates", "report.admin"],
    update: ["report.templates", "report.admin"],
    archive: ["report.admin"],
    restore: ["report.admin"],
    append: ["report.templates", "report.admin"],
  },
  report_generation_metadata: {
    list: ["report.audit", "report.view", "report.admin"],
    get: ["report.audit", "report.view", "report.admin"],
    search: ["report.audit", "report.view", "report.admin"],
    create: ["report.generate", "report.preview", "report.admin"],
    update: ["report.audit", "report.admin"],
    archive: ["report.audit", "report.admin"],
    restore: ["report.audit", "report.admin"],
    append: ["report.generate", "report.preview", "report.admin"],
  },
  traceability_link: {
    list: ["traceability.list", "traceability.admin"],
    get: ["traceability.read", "traceability.admin"],
    search: ["traceability.list", "traceability.admin"],
    create: ["traceability.link", "traceability.admin"],
    update: ["traceability.link", "traceability.admin"],
    archive: ["traceability.admin"],
    restore: ["traceability.admin"],
    append: ["traceability.link", "traceability.admin"],
  },
  audit_record: {
    list: ["testing.admin", "administration.testing"],
    get: ["testing.admin", "administration.testing"],
    search: ["testing.admin", "administration.testing"],
    create: ["testing.admin", "administration.testing"],
    update: ["testing.admin", "administration.testing"],
    archive: ["testing.admin", "administration.testing"],
    restore: ["testing.admin", "administration.testing"],
    append: ["testing.admin", "administration.testing"],
  },
  configuration: {
    list: ["testing.admin", "administration.testing"],
    get: ["testing.admin", "administration.testing"],
    search: ["testing.admin", "administration.testing"],
    create: ["testing.admin", "administration.testing"],
    update: ["testing.admin", "administration.testing"],
    archive: ["testing.admin", "administration.testing"],
    restore: ["testing.admin", "administration.testing"],
    append: ["testing.admin", "administration.testing"],
  },
  registry_entry: {
    list: ["testing.admin", "administration.testing"],
    get: ["testing.admin", "administration.testing"],
    search: ["testing.admin", "administration.testing"],
    create: ["testing.admin", "administration.testing"],
    update: ["testing.admin", "administration.testing"],
    archive: ["testing.admin", "administration.testing"],
    restore: ["testing.admin", "administration.testing"],
    append: ["testing.admin", "administration.testing"],
  },
};

export function permissionsForOperation(
  kind: AggregateKind,
  operation: RepositoryOperation,
): readonly string[] {
  return OPERATION_PERMISSION_MAP[kind][operation];
}

/** True when any granted pattern matches any required permission key. */
export function hasAnyMatchingPermission(
  granted: readonly string[],
  required: readonly string[],
): boolean {
  return required.some((needed) =>
    granted.some((pattern) => permissionPatternMatches(pattern, needed)),
  );
}

/**
 * Assert the context holds at least one matching permission for the operation.
 * No allow-all mode — callers must supply matching grants (including namespace wildcards).
 */
export function assertPermission(
  ctx: RepositoryContext,
  kind: AggregateKind,
  operation: RepositoryOperation,
): void {
  const required = permissionsForOperation(kind, operation);
  if (!hasAnyMatchingPermission(ctx.permissions, required)) {
    throw unauthorizedError(required[0] ?? "unknown", ctx.actorUserId);
  }
}
