import type { ConfigVariableDefinition } from "./types";

export const PLATFORM_CONFIG_REGISTRY: readonly ConfigVariableDefinition[] = [
  {
    key: "NODE_ENV",
    type: "enum",
    defaultValue: "development",
    description: "Node.js runtime environment profile.",
    owner: "platform",
    scope: "all",
    secret: "none",
    required: true,
    enumValues: ["development", "test", "production"],
  },
  {
    key: "PORT",
    type: "number",
    defaultValue: 3300,
    description: "HTTP listen port for the application server.",
    owner: "platform",
    scope: "all",
    secret: "none",
  },
  {
    key: "APP_URL",
    type: "url",
    defaultValue: "http://localhost:3300",
    description: "Canonical public application URL.",
    owner: "platform",
    scope: "all",
    secret: "none",
    required: true,
  },
  {
    key: "NEXT_PUBLIC_APP_URL",
    type: "url",
    description: "Public application URL exposed to the browser.",
    owner: "presentation",
    scope: "all",
    secret: "public",
  },
  {
    key: "ALLOW_DEV_REGISTRATION",
    type: "boolean",
    defaultValue: false,
    description: "Permits self-service registration in development only.",
    owner: "identity",
    scope: ["development"],
    secret: "none",
  },
  {
    key: "NEXT_PUBLIC_ALLOW_DEV_REGISTRATION",
    type: "boolean",
    description: "Client-visible dev registration flag.",
    owner: "presentation",
    scope: ["development"],
    secret: "public",
  },
  {
    key: "PLATFORM_VERSION",
    type: "string",
    defaultValue: "0.0.0",
    description: "Platform semantic version reported in health probes.",
    owner: "platform",
    scope: "all",
    secret: "none",
  },
  {
    key: "BUILD_NUMBER",
    type: "string",
    defaultValue: "local",
    description: "Build identifier reported in health probes.",
    owner: "platform",
    scope: "all",
    secret: "none",
  },
  {
    key: "DATABASE_URL",
    type: "string",
    description: "PostgreSQL connection string for platform metadata.",
    owner: "platform",
    scope: "all",
    secret: "connection-string",
    required: true,
  },
  {
    key: "DATABASE_URL_TEST",
    type: "string",
    description: "Optional PostgreSQL connection string for integration tests.",
    owner: "platform",
    scope: ["test", "development"],
    secret: "connection-string",
  },
  {
    key: "REDIS_URL",
    type: "string",
    description: "Redis connection string for rate limiting and caching.",
    owner: "platform",
    scope: "all",
    secret: "connection-string",
    required: true,
  },
  {
    key: "BETTER_AUTH_SECRET",
    type: "string",
    description: "Signing secret for Better Auth session tokens.",
    owner: "identity",
    scope: "all",
    secret: "secret",
    required: true,
    minLength: 32,
  },
  {
    key: "BETTER_AUTH_URL",
    type: "url",
    description: "Base URL for Better Auth callbacks.",
    owner: "identity",
    scope: "all",
    secret: "none",
    required: true,
  },
  {
    key: "EMAIL_FROM",
    type: "email",
    defaultValue: "noreply@apzhub.local",
    description: "Default sender address for platform email.",
    owner: "platform",
    scope: "all",
    secret: "none",
  },
  {
    key: "SMTP_HOST",
    type: "string",
    description: "SMTP hostname (prefer `.secrets/smtp`).",
    owner: "platform",
    scope: "all",
    secret: "none",
  },
  {
    key: "SMTP_PORT",
    type: "number",
    description: "SMTP port.",
    owner: "platform",
    scope: "all",
    secret: "none",
  },
  {
    key: "SMTP_USER",
    type: "string",
    description: "SMTP username.",
    owner: "platform",
    scope: "all",
    secret: "credential",
  },
  {
    key: "SMTP_PASS",
    type: "string",
    description: "SMTP password / app password.",
    owner: "platform",
    scope: "all",
    secret: "secret",
  },
  {
    key: "SMTP_FROM",
    type: "email",
    description: "SMTP From address override.",
    owner: "platform",
    scope: "all",
    secret: "none",
  },
  {
    key: "OPENAI_API_KEY",
    type: "string",
    description: "OpenAI API key (prefer `.secrets/openai`).",
    owner: "platform",
    scope: "all",
    secret: "secret",
  },
  {
    key: "GITHUB_TOKEN",
    type: "string",
    description: "GitHub PAT (prefer `.secrets/git`).",
    owner: "platform",
    scope: "all",
    secret: "secret",
  },
  {
    key: "APZHUB_SCM_GITHUB_TOKEN",
    type: "string",
    description: "SCM GitHub token alias.",
    owner: "platform",
    scope: "all",
    secret: "secret",
  },
  {
    key: "LAW_REPOSITORY_MODE",
    type: "enum",
    defaultValue: "memory",
    description: "Law platform persistence backend selection.",
    owner: "law-platform",
    scope: "all",
    secret: "none",
    enumValues: ["memory", "postgres"],
  },
  {
    key: "ENTITY_MAPPING_STORE_MODE",
    type: "enum",
    defaultValue: "memory",
    description:
      "Entity mapping store backend — memory (tests/dev) or postgres (production-capable). Never silently falls back.",
    owner: "platform",
    scope: "all",
    secret: "none",
    enumValues: ["memory", "postgres"],
  },
  {
    key: "ENTITY_MAPPING_ALLOW_MEMORY_IN_PRODUCTION",
    type: "boolean",
    defaultValue: "false",
    description:
      "Explicit escape hatch to allow in-memory entity mapping store when NODE_ENV=production.",
    owner: "platform",
    scope: ["production"],
    secret: "none",
  },
  {
    key: "AUTHORIZATION_PROVIDER_MODE",
    type: "enum",
    defaultValue: "allow-all",
    description:
      "Platform service authorisation provider — production, allow-all (dev/test), or deny-all (tests). Never silently allow-all in production.",
    owner: "platform",
    scope: "all",
    secret: "none",
    enumValues: ["production", "allow-all", "deny-all"],
  },
  {
    key: "AUTHORIZATION_ALLOW_ALL_IN_PRODUCTION",
    type: "boolean",
    defaultValue: "false",
    description:
      "Explicit escape hatch to allow allow-all authorisation when NODE_ENV=production.",
    owner: "platform",
    scope: ["production"],
    secret: "none",
  },
  {
    key: "LAW_TENANT_ID",
    type: "string",
    description: "Optional default tenant identifier for law persistence.",
    owner: "law-platform",
    scope: ["development", "test"],
    secret: "none",
  },
  {
    key: "LAW_OUTBOX_ENABLED",
    type: "boolean",
    description: "Enables transactional outbox writes in postgres law mode.",
    owner: "law-platform",
    scope: "all",
    secret: "none",
  },
  {
    key: "CADDY_HTTP_PORT",
    type: "number",
    defaultValue: 3080,
    description: "Host HTTP port when using Docker Compose Caddy.",
    owner: "infrastructure",
    scope: "all",
    secret: "none",
  },
  {
    key: "CADDY_HTTPS_PORT",
    type: "number",
    defaultValue: 3443,
    description: "Host HTTPS port when using Docker Compose Caddy.",
    owner: "infrastructure",
    scope: "all",
    secret: "none",
  },
  {
    key: "PLANE_INTEGRATION_ENABLED",
    type: "boolean",
    defaultValue: false,
    description:
      "Enables the Plane engine integration behind APZHUB Projects. When false, Plane config is ignored.",
    owner: "integrations",
    scope: "all",
    secret: "none",
  },
  {
    key: "PLANE_BASE_URL",
    type: "url",
    description:
      "Plane CE web origin (internal). Used for adapter connectivity checks — not exposed to users.",
    owner: "integrations",
    scope: "all",
    secret: "none",
  },
  {
    key: "PLANE_API_BASE_URL",
    type: "url",
    description:
      "Plane CE REST API base URL (typically {PLANE_BASE_URL}/api). Adapter-only — never client-facing.",
    owner: "integrations",
    scope: "all",
    secret: "none",
  },
  {
    key: "PLANE_API_TOKEN",
    type: "string",
    description:
      "Plane service account API token for adapter authentication. Per-tenant tokens deferred to PCv2-04 vault.",
    owner: "integrations",
    scope: "all",
    secret: "credential",
    minLength: 16,
  },
  {
    key: "PLANE_WORKSPACE_ID",
    type: "string",
    description:
      "Default Plane workspace identifier for single-tenant dev/staging. Production uses per-tenant provisioning metadata.",
    owner: "integrations",
    scope: ["development", "test"],
    secret: "none",
  },
  {
    key: "PLANE_WEBHOOK_SECRET",
    type: "string",
    description:
      "Shared secret for validating inbound Plane webhooks (OSS-101-08+). Optional until webhook phase.",
    owner: "integrations",
    scope: "all",
    secret: "secret",
    minLength: 16,
  },
] as const;

export const KNOWN_CONFIG_KEYS = new Set(
  PLATFORM_CONFIG_REGISTRY.map((definition) => definition.key),
);

export function getConfigDefinition(key: string): ConfigVariableDefinition | undefined {
  return PLATFORM_CONFIG_REGISTRY.find((definition) => definition.key === key);
}
