/**
 * Platform Observability metadata schema (APZOBSERVE-001).
 * Metadata SoR only — not Prometheus / Loki / Grafana storage.
 */
import {
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  varchar,
} from "drizzle-orm/pg-core";

export const platformObserveHealthCheck = pgTable("platform_observe_health_check", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  serviceKey: text("service_key").notNull(),
  name: text("name").notNull(),
  description: text("description"),
  status: varchar("status", { length: 32 }).notNull(),
  checkedAt: timestamp("checked_at", { withTimezone: true }),
  providerKind: varchar("provider_kind", { length: 32 }).notNull(),
  providerRef: text("provider_ref"),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformObserveReadinessCheck = pgTable("platform_observe_readiness_check", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  serviceKey: text("service_key").notNull(),
  name: text("name").notNull(),
  status: varchar("status", { length: 32 }).notNull(),
  checkedAt: timestamp("checked_at", { withTimezone: true }),
  providerKind: varchar("provider_kind", { length: 32 }).notNull(),
  providerRef: text("provider_ref"),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformObserveLivenessCheck = pgTable("platform_observe_liveness_check", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  serviceKey: text("service_key").notNull(),
  name: text("name").notNull(),
  status: varchar("status", { length: 32 }).notNull(),
  checkedAt: timestamp("checked_at", { withTimezone: true }),
  providerKind: varchar("provider_kind", { length: 32 }).notNull(),
  providerRef: text("provider_ref"),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformObserveServiceHealth = pgTable("platform_observe_service_health", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  serviceKey: text("service_key").notNull(),
  displayName: text("display_name").notNull(),
  overallStatus: varchar("overall_status", { length: 32 }).notNull(),
  readinessStatus: varchar("readiness_status", { length: 32 }).notNull(),
  livenessStatus: varchar("liveness_status", { length: 32 }).notNull(),
  lastEvaluatedAt: timestamp("last_evaluated_at", { withTimezone: true }),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformObserveServiceStatus = pgTable("platform_observe_service_status", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  serviceKey: text("service_key").notNull(),
  status: varchar("status", { length: 32 }).notNull(),
  message: text("message"),
  observedAt: timestamp("observed_at", { withTimezone: true }),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformObserveComponentStatus = pgTable("platform_observe_component_status", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  serviceKey: text("service_key").notNull(),
  componentKey: text("component_key").notNull(),
  name: text("name").notNull(),
  status: varchar("status", { length: 32 }).notNull(),
  message: text("message"),
  observedAt: timestamp("observed_at", { withTimezone: true }),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformObserveMetricDefinition = pgTable("platform_observe_metric_definition", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  key: text("key").notNull(),
  name: text("name").notNull(),
  description: text("description"),
  kind: varchar("kind", { length: 32 }).notNull(),
  unit: text("unit"),
  providerKind: varchar("provider_kind", { length: 32 }).notNull(),
  providerRef: text("provider_ref"),
  status: varchar("status", { length: 32 }).notNull(),
  labels: jsonb("labels_json").$type<Record<string, string>>().default({}),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformObserveMetricSample = pgTable("platform_observe_metric_sample", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  metricDefinitionId: text("metric_definition_id").notNull(),
  sampledAt: timestamp("sampled_at", { withTimezone: true }).notNull(),
  valueLabel: text("value_label"),
  providerKind: varchar("provider_kind", { length: 32 }).notNull(),
  providerRef: text("provider_ref"),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformObserveAlertDefinition = pgTable("platform_observe_alert_definition", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  key: text("key").notNull(),
  name: text("name").notNull(),
  description: text("description"),
  severity: varchar("severity", { length: 32 }).notNull(),
  providerKind: varchar("provider_kind", { length: 32 }).notNull(),
  providerRef: text("provider_ref"),
  status: varchar("status", { length: 32 }).notNull(),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformObserveAlertState = pgTable("platform_observe_alert_state", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  alertDefinitionId: text("alert_definition_id").notNull(),
  state: varchar("state", { length: 32 }).notNull(),
  firedAt: timestamp("fired_at", { withTimezone: true }),
  resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  message: text("message"),
  providerKind: varchar("provider_kind", { length: 32 }).notNull(),
  providerRef: text("provider_ref"),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformObserveDashboard = pgTable("platform_observe_dashboard", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  key: text("key").notNull(),
  name: text("name").notNull(),
  description: text("description"),
  providerKind: varchar("provider_kind", { length: 32 }).notNull(),
  providerRef: text("provider_ref"),
  status: varchar("status", { length: 32 }).notNull(),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformObserveLogSource = pgTable("platform_observe_log_source", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  key: text("key").notNull(),
  name: text("name").notNull(),
  kind: varchar("kind", { length: 32 }).notNull(),
  providerKind: varchar("provider_kind", { length: 32 }).notNull(),
  providerRef: text("provider_ref"),
  status: varchar("status", { length: 32 }).notNull(),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformObserveTraceDefinition = pgTable("platform_observe_trace_definition", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  key: text("key").notNull(),
  name: text("name").notNull(),
  description: text("description"),
  providerKind: varchar("provider_kind", { length: 32 }).notNull(),
  providerRef: text("provider_ref"),
  status: varchar("status", { length: 32 }).notNull(),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformObserveTraceSpan = pgTable("platform_observe_trace_span", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  traceDefinitionId: text("trace_definition_id").notNull(),
  spanName: text("span_name").notNull(),
  serviceKey: text("service_key"),
  startedAt: timestamp("started_at", { withTimezone: true }),
  endedAt: timestamp("ended_at", { withTimezone: true }),
  providerKind: varchar("provider_kind", { length: 32 }).notNull(),
  providerRef: text("provider_ref"),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformObserveIncidentReference = pgTable("platform_observe_incident_reference", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  key: text("key").notNull(),
  title: text("title").notNull(),
  serviceKey: text("service_key"),
  alertDefinitionId: text("alert_definition_id"),
  status: varchar("status", { length: 32 }).notNull(),
  externalRef: text("external_ref"),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformObserveMaintenanceWindow = pgTable("platform_observe_maintenance_window", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  key: text("key").notNull(),
  name: text("name").notNull(),
  serviceKey: text("service_key"),
  startsAt: timestamp("starts_at", { withTimezone: true }).notNull(),
  endsAt: timestamp("ends_at", { withTimezone: true }).notNull(),
  status: varchar("status", { length: 32 }).notNull(),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformObserveHealthSummary = pgTable("platform_observe_health_summary", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  scopeKey: text("scope_key").notNull(),
  overallStatus: varchar("overall_status", { length: 32 }).notNull(),
  healthyCount: integer("healthy_count").notNull(),
  degradedCount: integer("degraded_count").notNull(),
  unhealthyCount: integer("unhealthy_count").notNull(),
  evaluatedAt: timestamp("evaluated_at", { withTimezone: true }).notNull(),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformObserveDiagnostic = pgTable("platform_observe_diagnostic", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  key: text("key").notNull(),
  name: text("name").notNull(),
  serviceKey: text("service_key"),
  status: varchar("status", { length: 32 }).notNull(),
  detail: text("detail"),
  providerKind: varchar("provider_kind", { length: 32 }).notNull(),
  providerRef: text("provider_ref"),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformObserveMetadata = pgTable("platform_observe_metadata", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  key: text("key").notNull(),
  name: text("name").notNull(),
  category: text("category").notNull(),
  status: varchar("status", { length: 32 }).notNull(),
  payload: jsonb("payload_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformObserveSchema = {
  platformObserveHealthCheck,
  platformObserveReadinessCheck,
  platformObserveLivenessCheck,
  platformObserveServiceHealth,
  platformObserveServiceStatus,
  platformObserveComponentStatus,
  platformObserveMetricDefinition,
  platformObserveMetricSample,
  platformObserveAlertDefinition,
  platformObserveAlertState,
  platformObserveDashboard,
  platformObserveLogSource,
  platformObserveTraceDefinition,
  platformObserveTraceSpan,
  platformObserveIncidentReference,
  platformObserveMaintenanceWindow,
  platformObserveHealthSummary,
  platformObserveDiagnostic,
  platformObserveMetadata,
} as const;
