/**
 * Platform Metrics metadata schema (APZMETRICS-001).
 * Metadata SoR only — not Prometheus / Grafana / OTel storage or execution.
 */
import { integer, jsonb, pgTable, text, timestamp, varchar } from "drizzle-orm/pg-core";

export const platformMetricsMetric = pgTable("platform_metrics_metric", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  key: text("key").notNull(),
  name: text("name").notNull(),
  description: text("description"),
  categoryId: text("category_id"),
  groupId: text("group_id"),
  classificationId: text("classification_id"),
  currentVersionId: text("current_version_id"),
  ownerRef: text("owner_ref"),
  status: varchar("status", { length: 64 }).notNull(),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformMetricsDefinition = pgTable("platform_metrics_definition", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  metricId: text("metric_id").notNull(),
  key: text("key").notNull(),
  name: text("name").notNull(),
  description: text("description"),
  kind: varchar("kind", { length: 64 }).notNull(),
  unitId: text("unit_id"),
  formulaId: text("formula_id"),
  aggregationId: text("aggregation_id"),
  versionNumber: integer("version_number").notNull(),
  status: varchar("status", { length: 64 }).notNull(),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformMetricsVersion = pgTable("platform_metrics_version", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  metricId: text("metric_id").notNull(),
  versionNumber: integer("version_number").notNull(),
  status: varchar("status", { length: 64 }).notNull(),
  changeSummary: text("change_summary"),
  effectiveFrom: text("effective_from"),
  effectiveTo: text("effective_to"),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformMetricsCategory = pgTable("platform_metrics_category", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  key: text("key").notNull(),
  name: text("name").notNull(),
  description: text("description"),
  parentCategoryId: text("parent_category_id"),
  status: varchar("status", { length: 64 }).notNull(),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformMetricsGroup = pgTable("platform_metrics_group", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  key: text("key").notNull(),
  name: text("name").notNull(),
  description: text("description"),
  categoryId: text("category_id"),
  status: varchar("status", { length: 64 }).notNull(),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformMetricsDimension = pgTable("platform_metrics_dimension", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  key: text("key").notNull(),
  name: text("name").notNull(),
  description: text("description"),
  dataType: varchar("data_type", { length: 64 }).notNull(),
  metricId: text("metric_id"),
  status: varchar("status", { length: 64 }).notNull(),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformMetricsLabel = pgTable("platform_metrics_label", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  key: text("key").notNull(),
  name: text("name").notNull(),
  description: text("description"),
  metricId: text("metric_id"),
  status: varchar("status", { length: 64 }).notNull(),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformMetricsUnit = pgTable("platform_metrics_unit", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  key: text("key").notNull(),
  name: text("name").notNull(),
  symbol: text("symbol"),
  quantityKind: text("quantity_kind"),
  status: varchar("status", { length: 64 }).notNull(),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformMetricsFormula = pgTable("platform_metrics_formula", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  metricId: text("metric_id"),
  expression: text("expression").notNull(),
  description: text("description"),
  language: varchar("language", { length: 64 }).notNull(),
  status: varchar("status", { length: 64 }).notNull(),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformMetricsAggregation = pgTable("platform_metrics_aggregation", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  key: text("key").notNull(),
  name: text("name").notNull(),
  method: varchar("method", { length: 64 }).notNull(),
  windowHint: text("window_hint"),
  status: varchar("status", { length: 64 }).notNull(),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformMetricsThreshold = pgTable("platform_metrics_threshold", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  metricId: text("metric_id").notNull(),
  name: text("name").notNull(),
  operator: varchar("operator", { length: 64 }).notNull(),
  valueLabel: text("value_label").notNull(),
  severity: varchar("severity", { length: 64 }).notNull(),
  status: varchar("status", { length: 64 }).notNull(),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformMetricsOwner = pgTable("platform_metrics_owner", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  metricId: text("metric_id").notNull(),
  ownerType: varchar("owner_type", { length: 64 }).notNull(),
  ownerRef: text("owner_ref").notNull(),
  displayName: text("display_name"),
  status: varchar("status", { length: 64 }).notNull(),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformMetricsConsumer = pgTable("platform_metrics_consumer", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  metricId: text("metric_id").notNull(),
  consumerType: varchar("consumer_type", { length: 64 }).notNull(),
  consumerRef: text("consumer_ref").notNull(),
  displayName: text("display_name"),
  status: varchar("status", { length: 64 }).notNull(),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformMetricsRetentionPolicy = pgTable(
  "platform_metrics_retention_policy",
  {
    id: text("id").primaryKey(),
    tenantId: text("tenant_id").notNull(),
    organisationId: text("organisation_id"),
    key: text("key").notNull(),
    name: text("name").notNull(),
    retentionDays: integer("retention_days").notNull(),
    metricId: text("metric_id"),
    status: varchar("status", { length: 64 }).notNull(),
    metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    createdBy: text("created_by").notNull(),
    updatedBy: text("updated_by").notNull(),
    revision: integer("revision").notNull().default(1),
  },
);

export const platformMetricsClassification = pgTable(
  "platform_metrics_classification",
  {
    id: text("id").primaryKey(),
    tenantId: text("tenant_id").notNull(),
    organisationId: text("organisation_id"),
    key: text("key").notNull(),
    name: text("name").notNull(),
    level: varchar("level", { length: 64 }).notNull(),
    description: text("description"),
    status: varchar("status", { length: 64 }).notNull(),
    metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    createdBy: text("created_by").notNull(),
    updatedBy: text("updated_by").notNull(),
    revision: integer("revision").notNull().default(1),
  },
);

export const platformMetricsDependency = pgTable("platform_metrics_dependency", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  metricId: text("metric_id").notNull(),
  dependsOnMetricId: text("depends_on_metric_id").notNull(),
  dependencyKind: varchar("dependency_kind", { length: 64 }).notNull(),
  status: varchar("status", { length: 64 }).notNull(),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformMetricsKpi = pgTable("platform_metrics_kpi", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  key: text("key").notNull(),
  name: text("name").notNull(),
  description: text("description"),
  metricId: text("metric_id").notNull(),
  groupId: text("group_id"),
  classificationId: text("classification_id"),
  status: varchar("status", { length: 64 }).notNull(),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformMetricsKpiGroup = pgTable("platform_metrics_kpi_group", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  key: text("key").notNull(),
  name: text("name").notNull(),
  description: text("description"),
  status: varchar("status", { length: 64 }).notNull(),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformMetricsKpiTarget = pgTable("platform_metrics_kpi_target", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  kpiId: text("kpi_id").notNull(),
  periodLabel: text("period_label").notNull(),
  targetValueLabel: text("target_value_label").notNull(),
  unitId: text("unit_id"),
  status: varchar("status", { length: 64 }).notNull(),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformMetricsRelationship = pgTable("platform_metrics_relationship", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  fromMetricId: text("from_metric_id").notNull(),
  toMetricId: text("to_metric_id").notNull(),
  relationshipKind: varchar("relationship_kind", { length: 64 }).notNull(),
  status: varchar("status", { length: 64 }).notNull(),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformMetricsMetadata = pgTable("platform_metrics_metadata", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  organisationId: text("organisation_id"),
  subjectKind: text("subject_kind").notNull(),
  subjectId: text("subject_id").notNull(),
  key: text("key").notNull(),
  valueLabel: text("value_label"),
  status: varchar("status", { length: 64 }).notNull(),
  metadata: jsonb("metadata_json").$type<Record<string, unknown>>().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  revision: integer("revision").notNull().default(1),
});

export const platformMetricsSchema = {
  platformMetricsMetric,
  platformMetricsDefinition,
  platformMetricsVersion,
  platformMetricsCategory,
  platformMetricsGroup,
  platformMetricsDimension,
  platformMetricsLabel,
  platformMetricsUnit,
  platformMetricsFormula,
  platformMetricsAggregation,
  platformMetricsThreshold,
  platformMetricsOwner,
  platformMetricsConsumer,
  platformMetricsRetentionPolicy,
  platformMetricsClassification,
  platformMetricsDependency,
  platformMetricsKpi,
  platformMetricsKpiGroup,
  platformMetricsKpiTarget,
  platformMetricsRelationship,
  platformMetricsMetadata,
} as const;
