import type { ActivityRegistry } from "@apzhub/activity-timeline-framework/server";
import { TIMELINE_SCOPE_PERSONAL } from "@apzhub/activity-timeline-framework/server";

/** Placeholder Law Platform activity types — registration only (LAW-001-01). */
export function registerLawActivityTypes(registry: ActivityRegistry): void {
  const descriptors = [
    {
      activityTypeId: "legal.activity.dashboard.opened",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal-platform-module-opened",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-dashboard-opened",
      label: "Dashboard opened",
      description: "Placeholder activity when the Dashboard module is opened.",
      sourceCapability: "legal-platform",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.clients.viewed",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal-platform-module-opened",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-clients-viewed",
      label: "Clients viewed",
      description: "Placeholder activity when the Clients module is viewed.",
      sourceCapability: "legal-platform",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.matters.list.opened",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal-platform-module-opened",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-matters-opened",
      label: "Matter list opened",
      description: "Placeholder activity when the Matters module is opened.",
      sourceCapability: "legal-platform",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.client.opened",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.client.viewed",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-client-opened",
      label: "Client opened",
      description: "Placeholder activity when a client record is opened.",
      sourceCapability: "legal-clients",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.client.created",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.client.created",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-client-created",
      label: "Client created",
      description: "Placeholder activity when a client is created.",
      sourceCapability: "legal-clients",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.client.edited",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.client.updated",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-client-edited",
      label: "Client edited",
      description: "Placeholder activity when a client is edited.",
      sourceCapability: "legal-clients",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.client.deleted",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.client.deleted",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-client-deleted",
      label: "Client deleted",
      description: "Placeholder activity when a client is soft deleted.",
      sourceCapability: "legal-clients",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.matter.opened",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.matter.viewed",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-matter-opened",
      label: "Matter opened",
      description: "Placeholder activity when a matter record is opened.",
      sourceCapability: "legal-matters",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.matter.created",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.matter.created",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-matter-created",
      label: "Matter created",
      description: "Placeholder activity when a matter is created.",
      sourceCapability: "legal-matters",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.matter.edited",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.matter.updated",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-matter-edited",
      label: "Matter edited",
      description: "Placeholder activity when a matter is edited.",
      sourceCapability: "legal-matters",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.matter.archived",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.matter.archived",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-matter-archived",
      label: "Matter archived",
      description: "Placeholder activity when a matter is soft archived.",
      sourceCapability: "legal-matters",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.matter.workspace.opened",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.matter.workspace.opened",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-matter-workspace-opened",
      label: "Matter workspace opened",
      description: "Placeholder activity when the matter workspace is opened.",
      sourceCapability: "legal-matters",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.document.opened",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.document.viewed",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-document-opened",
      label: "Document opened",
      description: "Placeholder activity when a document record is opened.",
      sourceCapability: "legal-documents",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.document.created",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.document.created",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-document-created",
      label: "Document created",
      description: "Placeholder activity when a document is uploaded or created.",
      sourceCapability: "legal-documents",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.document.edited",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.document.updated",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-document-edited",
      label: "Document edited",
      description: "Placeholder activity when document metadata is edited.",
      sourceCapability: "legal-documents",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.document.archived",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.document.archived",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-document-archived",
      label: "Document archived",
      description: "Placeholder activity when a document is soft archived.",
      sourceCapability: "legal-documents",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.task.opened",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.task.viewed",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-task-opened",
      label: "Task opened",
      description: "Placeholder activity when a task record is opened.",
      sourceCapability: "legal-tasks",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.task.created",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.task.created",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-task-created",
      label: "Task created",
      description: "Placeholder activity when a task is created.",
      sourceCapability: "legal-tasks",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.task.edited",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.task.updated",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-task-edited",
      label: "Task edited",
      description: "Placeholder activity when a task is edited.",
      sourceCapability: "legal-tasks",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.task.completed",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.task.completed",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-task-completed",
      label: "Task completed",
      description: "Placeholder activity when a task is marked complete.",
      sourceCapability: "legal-tasks",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.task.archived",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.task.archived",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-task-archived",
      label: "Task archived",
      description: "Placeholder activity when a task is soft archived.",
      sourceCapability: "legal-tasks",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.time.opened",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.time.viewed",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-time-opened",
      label: "Time entry opened",
      description: "Placeholder activity when a time entry is opened.",
      sourceCapability: "legal-time",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.time.created",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.time.created",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-time-created",
      label: "Time entry created",
      description: "Placeholder activity when a time entry is created.",
      sourceCapability: "legal-time",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.time.edited",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.time.updated",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-time-edited",
      label: "Time entry edited",
      description: "Placeholder activity when a time entry is edited.",
      sourceCapability: "legal-time",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.time.deleted",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.time.deleted",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-time-deleted",
      label: "Time entry deleted",
      description: "Placeholder activity when a time entry is soft deleted.",
      sourceCapability: "legal-time",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.invoice.viewed",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.invoice.viewed",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-invoice-viewed",
      label: "Invoice viewed",
      description: "Placeholder activity when an invoice is opened.",
      sourceCapability: "legal-billing",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.invoice.created",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.invoice.created",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-invoice-created",
      label: "Invoice created",
      description: "Placeholder activity when an invoice is created.",
      sourceCapability: "legal-billing",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.invoice.updated",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.invoice.updated",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-invoice-updated",
      label: "Invoice updated",
      description: "Placeholder activity when an invoice is edited.",
      sourceCapability: "legal-billing",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.invoice.cancelled",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.invoice.cancelled",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-invoice-cancelled",
      label: "Invoice cancelled",
      description: "Placeholder activity when an invoice is voided.",
      sourceCapability: "legal-billing",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.invoice.paid",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.invoice.paid",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-invoice-paid",
      label: "Invoice paid",
      description: "Placeholder activity when an invoice is marked paid.",
      sourceCapability: "legal-billing",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.calendar.viewed",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.calendar.viewed",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-calendar-viewed",
      label: "Calendar event viewed",
      description: "Placeholder activity when a calendar event is opened.",
      sourceCapability: "legal-calendar",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.calendar.created",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.calendar.created",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-calendar-created",
      label: "Calendar event created",
      description: "Placeholder activity when a calendar event is created.",
      sourceCapability: "legal-calendar",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.calendar.edited",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.calendar.updated",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-calendar-edited",
      label: "Calendar event edited",
      description: "Placeholder activity when a calendar event is edited.",
      sourceCapability: "legal-calendar",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.calendar.cancelled",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.calendar.cancelled",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-calendar-cancelled",
      label: "Calendar event cancelled",
      description: "Placeholder activity when a calendar event is cancelled.",
      sourceCapability: "legal-calendar",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.search.executed",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.search.executed",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-search-executed",
      label: "Legal search executed",
      description: "Placeholder activity when unified legal search runs.",
      sourceCapability: "legal-search",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.search.result-opened",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.search.result.opened",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-search-result-opened",
      label: "Legal search result opened",
      description: "Placeholder activity when a search result is opened.",
      sourceCapability: "legal-search",
      source: "manifest" as const,
      status: "active" as const,
    },
    {
      activityTypeId: "legal.activity.search.filtered",
      version: "1.0.0",
      category: "capability" as const,
      sourceEventPattern: "legal.search.filtered",
      timelineScopes: [TIMELINE_SCOPE_PERSONAL],
      templateRef: "legal-activity-search-filtered",
      label: "Legal search filtered",
      description: "Placeholder activity when filtered legal search runs.",
      sourceCapability: "legal-search",
      source: "manifest" as const,
      status: "active" as const,
    },
  ];

  const pending = descriptors.filter(
    (descriptor) => !registry.has(descriptor.activityTypeId),
  );
  if (pending.length === 0) {
    return;
  }

  registry.registerManyAtomic(pending);
}
