/** Trust Allocation error codes (LAW-015-04). */

export const TRUST_ALLOCATION_ERROR_CODES = {
  TRUST_ALLOCATION_NOT_FOUND: "TRUST_ALLOCATION_NOT_FOUND",
  TRUST_ALLOCATION_INVALID: "TRUST_ALLOCATION_INVALID",
  TRUST_ALLOCATION_OVER_ALLOCATED: "TRUST_ALLOCATION_OVER_ALLOCATED",
  TRUST_ALLOCATION_UNDER_ALLOCATED: "TRUST_ALLOCATION_UNDER_ALLOCATED",
  TRUST_ALLOCATION_TRANSACTION_NOT_POSTED: "TRUST_ALLOCATION_TRANSACTION_NOT_POSTED",
  TRUST_ALLOCATION_TRANSACTION_NOT_FOUND: "TRUST_ALLOCATION_TRANSACTION_NOT_FOUND",
  TRUST_ALLOCATION_TENANT_MISMATCH: "TRUST_ALLOCATION_TENANT_MISMATCH",
  TRUST_ALLOCATION_CLIENT_MISMATCH: "TRUST_ALLOCATION_CLIENT_MISMATCH",
  TRUST_ALLOCATION_CURRENCY_MISMATCH: "TRUST_ALLOCATION_CURRENCY_MISMATCH",
  TRUST_ALLOCATION_NEGATIVE_AMOUNT: "TRUST_ALLOCATION_NEGATIVE_AMOUNT",
  TRUST_ALLOCATION_REVERSAL_INVALID: "TRUST_ALLOCATION_REVERSAL_INVALID",
  TRUST_ALLOCATION_ALREADY_REVERSED: "TRUST_ALLOCATION_ALREADY_REVERSED",
  TRUST_ALLOCATION_ADJUSTMENT_INVALID: "TRUST_ALLOCATION_ADJUSTMENT_INVALID",
} as const;

export type TrustAllocationErrorCode =
  (typeof TRUST_ALLOCATION_ERROR_CODES)[keyof typeof TRUST_ALLOCATION_ERROR_CODES];

export class TrustAllocationError extends Error {
  readonly code: TrustAllocationErrorCode;

  constructor(code: TrustAllocationErrorCode, message: string) {
    super(message);
    this.name = "TrustAllocationError";
    this.code = code;
  }
}

export function isTrustAllocationError(error: unknown): error is TrustAllocationError {
  return error instanceof TrustAllocationError;
}
