/** Trust Ledger Engine error codes (LAW-015-02). */

export const TRUST_LEDGER_ERROR_CODES = {
  TRUST_JOURNAL_UNBALANCED: "TRUST_JOURNAL_UNBALANCED",
  TRUST_ACCOUNT_NOT_FOUND: "TRUST_ACCOUNT_NOT_FOUND",
  TRUST_ACCOUNT_INACTIVE: "TRUST_ACCOUNT_INACTIVE",
  TRUST_TRANSACTION_NOT_FOUND: "TRUST_TRANSACTION_NOT_FOUND",
  TRUST_INSUFFICIENT_BALANCE: "TRUST_INSUFFICIENT_BALANCE",
  TRUST_INVALID_AMOUNT: "TRUST_INVALID_AMOUNT",
  TRUST_CURRENCY_MISMATCH: "TRUST_CURRENCY_MISMATCH",
  TRUST_TENANT_MISMATCH: "TRUST_TENANT_MISMATCH",
  TRUST_INVALID_DATE: "TRUST_INVALID_DATE",
  TRUST_INVALID_REFERENCE: "TRUST_INVALID_REFERENCE",
  TRUST_MISSING_CLIENT: "TRUST_MISSING_CLIENT",
  TRUST_MISSING_REVERSAL_TARGET: "TRUST_MISSING_REVERSAL_TARGET",
  TRUST_ALREADY_REVERSED: "TRUST_ALREADY_REVERSED",
  TRUST_REVERSAL_INVALID: "TRUST_REVERSAL_INVALID",
  TRUST_INVALID_ADJUSTMENT: "TRUST_INVALID_ADJUSTMENT",
  TRUST_IMMUTABLE_VIOLATION: "TRUST_IMMUTABLE_VIOLATION",
  TRUST_UNSUPPORTED_TYPE: "TRUST_UNSUPPORTED_TYPE",
} as const;

export type TrustLedgerErrorCode =
  (typeof TRUST_LEDGER_ERROR_CODES)[keyof typeof TRUST_LEDGER_ERROR_CODES];

export class TrustLedgerError extends Error {
  readonly code: TrustLedgerErrorCode;

  constructor(code: TrustLedgerErrorCode, message: string) {
    super(message);
    this.name = "TrustLedgerError";
    this.code = code;
  }
}

export function isTrustLedgerError(error: unknown): error is TrustLedgerError {
  return error instanceof TrustLedgerError;
}
