export const TRUST_INTEREST_ERROR_CODES = {
  TRUST_INTEREST_RULE_NOT_FOUND: "TRUST_INTEREST_RULE_NOT_FOUND",
  TRUST_INTEREST_RULE_INACTIVE: "TRUST_INTEREST_RULE_INACTIVE",
  TRUST_INTEREST_RULE_ACCOUNT_MISMATCH: "TRUST_INTEREST_RULE_ACCOUNT_MISMATCH",
  TRUST_INTEREST_POSTING_NOT_FOUND: "TRUST_INTEREST_POSTING_NOT_FOUND",
  TRUST_INTEREST_INVALID_STATUS: "TRUST_INTEREST_INVALID_STATUS",
  TRUST_INTEREST_INVALID_PERIOD: "TRUST_INTEREST_INVALID_PERIOD",
  TRUST_INTEREST_INVALID_RATE: "TRUST_INTEREST_INVALID_RATE",
  TRUST_INTEREST_NO_ACCRUAL_LINES: "TRUST_INTEREST_NO_ACCRUAL_LINES",
  TRUST_INTEREST_TENANT_MISMATCH: "TRUST_INTEREST_TENANT_MISMATCH",
  TRUST_INTEREST_ACCOUNT_NOT_FOUND: "TRUST_INTEREST_ACCOUNT_NOT_FOUND",
  TRUST_INTEREST_POST_FAILED: "TRUST_INTEREST_POST_FAILED",
  TRUST_INTEREST_FAILED: "TRUST_INTEREST_FAILED",
} as const;

export type TrustInterestErrorCode =
  (typeof TRUST_INTEREST_ERROR_CODES)[keyof typeof TRUST_INTEREST_ERROR_CODES];

export class TrustInterestError extends Error {
  readonly code: TrustInterestErrorCode;

  constructor(code: TrustInterestErrorCode, message: string) {
    super(message);
    this.name = "TrustInterestError";
    this.code = code;
  }
}

export function isTrustInterestError(error: unknown): error is TrustInterestError {
  return error instanceof TrustInterestError;
}
