/** Trust Approval error codes (LAW-015-10). */

export const TRUST_APPROVAL_ERROR_CODES = {
  TRUST_APPROVAL_NOT_FOUND: "TRUST_APPROVAL_NOT_FOUND",
  TRUST_APPROVAL_RULE_NOT_FOUND: "TRUST_APPROVAL_RULE_NOT_FOUND",
  TRUST_APPROVAL_TENANT_MISMATCH: "TRUST_APPROVAL_TENANT_MISMATCH",
  TRUST_APPROVAL_INVALID_STATUS: "TRUST_APPROVAL_INVALID_STATUS",
  TRUST_APPROVAL_INVALID_TRANSITION: "TRUST_APPROVAL_INVALID_TRANSITION",
  TRUST_APPROVAL_VALIDATION_FAILED: "TRUST_APPROVAL_VALIDATION_FAILED",
  TRUST_APPROVAL_DUPLICATE: "TRUST_APPROVAL_DUPLICATE",
  TRUST_APPROVAL_SELF_APPROVAL: "TRUST_APPROVAL_SELF_APPROVAL",
  TRUST_APPROVAL_ROLE_REQUIRED: "TRUST_APPROVAL_ROLE_REQUIRED",
  TRUST_APPROVAL_ALREADY_DECIDED: "TRUST_APPROVAL_ALREADY_DECIDED",
  TRUST_APPROVAL_NOT_APPROVED: "TRUST_APPROVAL_NOT_APPROVED",
  TRUST_APPROVAL_REQUIRED: "TRUST_APPROVAL_REQUIRED",
  TRUST_APPROVAL_FAILED: "TRUST_APPROVAL_FAILED",
} as const;

export type TrustApprovalErrorCode =
  (typeof TRUST_APPROVAL_ERROR_CODES)[keyof typeof TRUST_APPROVAL_ERROR_CODES];

export class TrustApprovalError extends Error {
  readonly code: TrustApprovalErrorCode;

  constructor(code: TrustApprovalErrorCode, message: string) {
    super(message);
    this.name = "TrustApprovalError";
    this.code = code;
  }
}

export function isTrustApprovalError(error: unknown): error is TrustApprovalError {
  return error instanceof TrustApprovalError;
}
