export const TRUST_TRANSFER_ERROR_CODES = {
  TRUST_TRANSFER_NOT_FOUND: "TRUST_TRANSFER_NOT_FOUND",
  TRUST_TRANSFER_INVALID_STATUS: "TRUST_TRANSFER_INVALID_STATUS",
  TRUST_TRANSFER_INVALID_TYPE: "TRUST_TRANSFER_INVALID_TYPE",
  TRUST_TRANSFER_TENANT_MISMATCH: "TRUST_TRANSFER_TENANT_MISMATCH",
  TRUST_TRANSFER_ACCOUNT_NOT_FOUND: "TRUST_TRANSFER_ACCOUNT_NOT_FOUND",
  TRUST_TRANSFER_ACCOUNT_INACTIVE: "TRUST_TRANSFER_ACCOUNT_INACTIVE",
  TRUST_TRANSFER_CURRENCY_MISMATCH: "TRUST_TRANSFER_CURRENCY_MISMATCH",
  TRUST_TRANSFER_INSUFFICIENT_BALANCE: "TRUST_TRANSFER_INSUFFICIENT_BALANCE",
  TRUST_TRANSFER_INVALID_AMOUNT: "TRUST_TRANSFER_INVALID_AMOUNT",
  TRUST_TRANSFER_REASON_REQUIRED: "TRUST_TRANSFER_REASON_REQUIRED",
  TRUST_TRANSFER_SAME_ENDPOINT: "TRUST_TRANSFER_SAME_ENDPOINT",
  TRUST_TRANSFER_REVERSAL_INVALID: "TRUST_TRANSFER_REVERSAL_INVALID",
  TRUST_TRANSFER_ALREADY_REVERSED: "TRUST_TRANSFER_ALREADY_REVERSED",
  TRUST_TRANSFER_VALIDATION_FAILED: "TRUST_TRANSFER_VALIDATION_FAILED",
  TRUST_TRANSFER_POST_FAILED: "TRUST_TRANSFER_POST_FAILED",
  TRUST_TRANSFER_FAILED: "TRUST_TRANSFER_FAILED",
} as const;

export type TrustTransferErrorCode =
  (typeof TRUST_TRANSFER_ERROR_CODES)[keyof typeof TRUST_TRANSFER_ERROR_CODES];

export class TrustTransferError extends Error {
  readonly code: TrustTransferErrorCode;

  constructor(code: TrustTransferErrorCode, message: string) {
    super(message);
    this.name = "TrustTransferError";
    this.code = code;
  }
}

export function isTrustTransferError(error: unknown): error is TrustTransferError {
  return error instanceof TrustTransferError;
}
