export type { AuditFields } from "./audit";
export type { Requirement, Risk, WorkItemRef } from "./requirement";
export type {
  TestPlan,
  TestSuite,
  TestCase,
  TestCaseParameter,
  TestCaseVersion,
  TestStep,
  RegressionSuite,
} from "./test-structure";
export type {
  ExecutionSession,
  ExecutionComment,
  ManualExecution,
  ManualStepActual,
  AutomatedExecution,
  TestRun,
  TestResult,
} from "./execution";
export type {
  Evidence,
  EvidenceRelationship,
  Attachment,
  DefectLink,
} from "./evidence";
export type {
  QualityGate,
  Signature,
  Witness,
  Approval,
  ApprovalHistoryEntry,
  ApprovalStageConfig,
  ApprovalStageDecision,
  CertificationGateDefinition,
  CertificationGateEvaluation,
  CertificationRecommendation,
  CertificationRule,
  CertificationAuditEntry,
  CertificationHistoryEntry,
  CertificationEvidenceLinks,
  CertificationRecord,
  ReleaseReadiness,
  AuditEvent,
  CertificationPreparationSummary,
  ReleaseReadinessInputs,
} from "./certification";
export type {
  TraceabilityLink,
  CoverageMetric,
  AutomationJob,
  DashboardSnapshot,
  AISuggestion,
  TraceabilityMatrixRow,
} from "./analytics";
export type {
  QualityScope,
  CoverageComputationResult,
  QualityIntelligenceMetrics,
  QualitySnapshot,
  QualityTrendDelta,
  QualityTrendComparison,
  RegressionCaseKeyResult,
  RegressionAnalysisResult,
  ReadinessDimension,
  ReleaseReadinessAssessment,
  CertificationReadinessAssessment,
  RiskAggregationBucket,
  RiskAggregationSummary,
  QualitySummary,
} from "./quality";
export type {
  CanonicalAutomationEnvironment,
  CanonicalAutomationStep,
  CanonicalAutomationCase,
  CanonicalAutomationSuite,
  CanonicalAutomationEvidenceMeta,
  CanonicalAutomationCoverageSummary,
  CanonicalAutomationResult,
  AutomationAdapterInput,
  AutomationResultAdapter,
  AutomationImport,
  AutomatedExecutionIngestion,
  AutomationRun,
  AutomationResultItem,
  AutomationImportHistory,
  AutomationCoverageSnapshot,
  AutomationCertificationPreparationInputs,
  AutomationEvidenceRegistration,
} from "./automation-ingestion";
export type {
  GovernedProduct,
  ProductRegistry,
  ProductDependency,
  DependencyValidationResult,
  DependencyHealthSummary,
  ProductHealthSummary,
  PlatformReleaseScope,
  PlatformReleasePackage,
  PlatformReleaseCandidate,
  PlatformReleaseWindow,
  PlatformReleaseApproval,
  PlatformReleaseDecision,
  PlatformReleaseNote,
  PlatformReleaseEvidenceRef,
  PlatformReleaseManifest,
  PlatformReleaseSummary,
  PlatformRelease,
  ProductQualityContribution,
  PlatformQualityAggregate,
  MultiProductCertificationAggregate,
  PlatformReleaseReadinessAggregate,
  PlatformQualityDashboardSnapshot,
  PlatformCrossProductLink,
} from "./platform-quality";
export type {
  ReleaseWindow,
  ReleaseScope,
  ReleasePackage,
  ReleaseCandidate,
  ReleaseApproval,
  ReleaseDecision,
  ReleaseEvidence,
  ReleaseDependency,
  ReleaseNote,
  ReleaseManifest,
  ReleaseRiskAssessment,
  ReleaseReadinessSnapshot,
  ReleaseSummary,
  ReleaseAuditEntry,
  Release,
} from "./release-governance";
export type {
  PipelineStep,
  PipelineJob,
  PipelineStage,
  ArtifactReference,
  PipelineEnvironment,
  PipelineApproval,
  PipelineDuration,
  PipelineQueue,
  PipelineFailure,
  PipelineWarning,
  PipelineRetry,
  PipelineMetrics,
  PipelineSummary,
  PipelineResult,
  CanonicalPipelineResult,
  PipelineLogReference,
  PipelineVariable,
  PipelineSecretReference,
  PipelineTrigger,
  PipelineSource,
  PipelineEventRecord,
  PipelineStatus,
  PipelineLinks,
  Pipeline,
  PipelineImport,
  PipelineRun,
  PipelineImportHistory,
  PipelineResultAdapter,
} from "./cicd-pipeline";
export { DEFAULT_QUALITY_SCORE_WEIGHTS } from "./engineering-intelligence";
export type {
  EngineeringScope,
  QualityScoreWeights,
  QualityScoreInputs,
  QualityScoreComponent,
  QualityScore,
  QualityIndicator,
  EngineeringIndicator,
  EngineeringRiskFactor,
  EngineeringRiskSummary,
  EngineeringHealth,
  TrendPoint,
  TrendSeries,
  QualityTrend,
  CoverageTrend,
  ExecutionTrend,
  AutomationTrend,
  RegressionTrend,
  ReleaseTrend,
  CertificationTrend,
  DefectTrend,
  LeadTimeTrend,
  StabilityTrend,
  RiskTrend,
  VelocityTrend,
  HistoricalPeriod,
  HistoricalSnapshot,
  QualitySnapshotSummary,
  EngineeringSnapshot,
  BenchmarkComparison,
  Benchmark,
  Baseline,
  EngineeringAggregationInputs,
} from "./engineering-intelligence";
export type {
  ReportType,
  ReportOutputFormat,
  ReportBlock,
  ReportSection,
  ReportBranding,
  CanonicalReportDocument,
  ReportParameters,
  TemplateSectionDefinition,
  TemplateBlockDefinition,
  ReportTemplate,
  ReportRequest,
  ReportValidationResult,
  RenderedReportOutput,
  ReportGenerationMetadata,
  ReportGenerationResult,
  ReportDescriptor,
} from "./reporting";
export { REPORT_TYPES, REPORT_OUTPUT_FORMATS } from "./reporting";
