export { DesktopShell } from "./desktop-shell";
export type { DesktopShellProps } from "./desktop-shell";
export { WorkbenchCommandPalette } from "./command-palette";
export {
  buildCommandPaletteDiagnostics,
  mapActionsToPaletteItems,
  mapKnowledgeGroupsToPaletteItems,
  useCommandPaletteKnowledgeQuery,
  COMMAND_PALETTE_SURFACE,
  CONTEXT_MENU_SURFACE,
  KEYBOARD_SHORTCUT_SURFACE,
  COMMAND_PALETTE_QUERY_DEBOUNCE_MS,
  PLANNED_WORKBENCH_SURFACES,
  WORKBENCH_SURFACES,
  useCommandPaletteState,
  useDebouncedValue,
  type WorkbenchCommandPaletteProps,
  type CommandPaletteMode,
  type CommandPaletteState,
  type UseCommandPaletteStateOptions,
  type CommandPaletteSurfaceDiagnostics,
  type WorkbenchSurfaceDefinition,
  type WorkbenchSurfaceId,
  type WorkbenchSurfaceStatus,
} from "./command-palette";
export {
  ContextMenuProvider,
  WorkbenchContextMenu,
  buildContextMenuDiagnostics,
  mapActionsToContextMenuItems,
  toActionContextSnapshot,
  toActionSelectionSnapshot,
  useContextMenuProvider,
  type ContextMenuSurfaceDiagnostics,
  type WorkbenchContextMenuInput,
  type WorkbenchContextMenuProps,
} from "./context-menu";
export {
  ToolbarProvider,
  WorkbenchToolbar,
  buildToolbarDiagnostics,
  mapToolbarItems,
  TOOLBAR_SURFACE,
  useToolbarProvider,
  type ToolbarSurfaceDiagnostics,
  type WorkbenchToolbarProps,
} from "./toolbar";
export {
  COMMAND_PALETTE_SHORTCUT,
  isCommandPaletteShortcut,
  shouldIgnoreCommandPaletteShortcut,
  useCommandPaletteShortcut,
} from "./desktop-shell/palette-shortcut";
export {
  GlobalSearchDialog,
  type GlobalSearchDialogProps,
} from "./global-search/global-search-dialog";
export {
  GLOBAL_SEARCH_SHORTCUT,
  isGlobalSearchShortcut,
  useGlobalSearchShortcut,
} from "./global-search/global-search-shortcut";
export {
  buildGlobalShortcutShellDiagnostics,
  GLOBAL_SHORTCUT_SURFACE,
  type GlobalShortcutShellDiagnostics,
} from "./desktop-shell/global-shortcut-diagnostics";
export {
  shouldIgnoreGlobalShortcut,
  useGlobalShortcuts,
  type UseGlobalShortcutsOptions,
} from "./desktop-shell/global-shortcuts";
export {
  KnowledgeOverlay,
  KnowledgeOverlayExperience,
  WorkbenchKnowledgeOverlay,
  buildKnowledgeOverlayDiagnostics,
  buildSourceLabelLookup,
  countOverlayDocuments,
  createWorkbenchKnowledgeSelectionHandlers,
  delegateKnowledgeOverlaySelection,
  groupKnowledgeDocuments,
  resolveKnowledgeOverlaySelection,
  resolveKnowledgeSelectionKind,
  useKnowledgeOverlayState,
  useWorkbenchKnowledgeSelectionHandlers,
  KNOWLEDGE_OVERLAY_SURFACE,
  type KnowledgeOverlayDiagnostics,
  type KnowledgeOverlayEmptyState,
  type KnowledgeOverlayErrorState,
  type KnowledgeOverlayExperienceProps,
  type KnowledgeOverlayGroup,
  type KnowledgeOverlayItem,
  type KnowledgeOverlayLoadingState,
  type KnowledgeOverlayProps,
  type KnowledgeOverlaySelection,
  type KnowledgeOverlaySurfaceDiagnostics,
  type KnowledgeSelectionKind,
  type UseKnowledgeOverlayStateOptions,
  type WorkbenchKnowledgeOverlayProps,
  type WorkbenchKnowledgeSelectionHandlers,
} from "./knowledge-overlay";
export {
  NotificationBadge,
  NotificationPanel,
  NotificationBadgeExperience,
  NotificationPanelExperience,
  WorkbenchNotifications,
  buildNotificationExperienceDiagnostics,
  delegateNotificationActionRef,
  useNotificationPanelState,
  NOTIFICATION_BADGE_SURFACE,
  NOTIFICATION_PANEL_SURFACE,
  type NotificationExperienceDiagnostics,
  type NotificationPanelEmptyState,
  type WorkbenchNotificationsProps,
  type NotificationActionExecutor,
  type NotificationPanelState,
  type UseNotificationPanelStateOptions,
} from "./notifications";
export {
  WorkbenchContextPanel,
  WorkbenchContextPanelActivityTab,
  useContextPanelState,
  CONTEXT_PANEL_SURFACE,
  CONTEXT_PANEL_ACTIVITY_SURFACE,
  type WorkbenchContextPanelProps,
  type WorkbenchContextPanelActivityTabProps,
  type ContextPanelState,
  type UseContextPanelStateOptions,
  type UseContextPanelStateResult,
} from "./context-panel";
