export const INTEGRATION_SDK_VERSION = "0.9.0";
export const INTEGRATION_SDK_PACKAGE = "@apzhub/integration-sdk";

export type {
  Connection,
  ConnectionConfig,
  ConnectionState,
  IntegrationCapabilityMetadata,
  IntegrationCredentials,
  IntegrationCredentialKind,
  IntegrationRequestContext,
  TransportKind,
  VendorVersionInfo,
  VersionCompatibilityResult,
  VersionCompatibilityStatus,
  VersionRange,
} from "./types";

export type {
  AdapterBase,
  PlaceholderAdapterBaseOptions,
  IntegrationCapabilityId,
  AdapterManifest,
  AdapterConnectionDefaults,
  AdapterBootstrapConfiguration,
  AdapterLifecycleResult,
  AdapterConfigurationValidationResult,
  AdapterDisposeReason,
  AdapterDisposeResult,
  AdapterContext,
  AdapterClock,
  BuildAdapterContextInput,
  RegisteredCapabilityRecord,
  CapabilityRegistrationResult,
  CapabilityDiscoveryFilter,
  CapabilityRegistration,
  AdapterConstructor,
  AdapterFactoryOptions,
  CreateAdapterOptions,
  AdapterFactoryCreateResult,
} from "./adapter";
export {
  PlaceholderAdapterBase,
  createPlaceholderAdapterBase,
  INTEGRATION_CAPABILITIES,
  isIntegrationCapabilityId,
  parseIntegrationCapabilities,
  buildAdapterContext,
  IntegrationAdapterBase,
  InMemoryCapabilityRegistration,
  createInMemoryCapabilityRegistration,
  validateAdapterManifest,
  AdapterFactory,
  createAdapterFactory,
  MockAdapter,
  createMockAdapterManifest,
} from "./adapter";

export type {
  IntegrationClient,
  IntegrationHttpMethod,
  IntegrationRequestOptions,
  IntegrationResponse,
  FetchFn as IntegrationFetchFn,
  CreateHttpIntegrationClientOptions,
} from "./client";
export {
  PlaceholderIntegrationClient,
  createPlaceholderIntegrationClient,
  HttpIntegrationClient,
  createHttpIntegrationClient,
} from "./client";

export type {
  TransportClient,
  TransportRequest,
  TransportResponse,
  TransportHeaders,
  TransportContext,
  TransportPipeline,
  TransportPolicy,
  TransportInterceptor,
  TransportExecutionContext,
  TransportDiagnostics,
  TransportMetrics,
  TransportMetricsSnapshot,
  TransportLogger,
  TransportConfiguration,
  TransportCapabilities,
  CreateTransportClientOptions,
  FetchFn,
  MockTransportOptions,
} from "./transport";
export {
  createTransportClient,
  DefaultTransportClient,
  createMockTransport,
  MockTransportClient,
  createCircuitBreakerInterceptor,
  createTransportMetrics,
  createTransportLogger,
} from "./transport";

export type {
  IntegrationDiagnostics,
  IntegrationHealth,
  IntegrationHealthCheck,
  IntegrationHealthCheckStatus,
  IntegrationHealthStatus,
  DiagnosticsCollectContext,
  DiagnosticsProvider,
  IntegrationErrorSummary,
  IntegrationRegistrationStatus,
  IntegrationVersionDiagnostics,
} from "./diagnostics";
export {
  DefaultDiagnosticsProvider,
  buildUnifiedIntegrationDiagnostics,
  createDefaultDiagnosticsProvider,
  createPlaceholderIntegrationDiagnostics,
  createPlaceholderIntegrationHealth,
} from "./diagnostics";
export type {
  CreatePlaceholderDiagnosticsInput,
  DefaultDiagnosticsProviderOptions,
  BuildUnifiedIntegrationDiagnosticsInput,
} from "./diagnostics";

export type {
  HealthCheckContext,
  HealthProvider,
  StandardHealthCheckName,
} from "./health";
export {
  CRITICAL_HEALTH_CHECK_NAMES,
  DefaultHealthProvider,
  STANDARD_HEALTH_CHECK_NAMES,
  aggregateHealthChecks,
  createDefaultHealthProvider,
  mapConnectionLifecycleToHealthSignal,
} from "./health";
export type { DefaultHealthProviderOptions } from "./health";

export type { VersionProbeInput, VersionProvider } from "./version";
export {
  DefaultVersionProvider,
  checkVersionCompatibility,
  createDefaultVersionProvider,
  extractDeclaredVersionRange,
  extractDetectedVersion,
} from "./version";

export type { IntegrationLifecycleState } from "./lifecycle";
export type {
  IntegrationLifecycleContext,
  IntegrationLifecycleParticipant,
  IntegrationLifecycleResult,
  IntegrationLifecycleParticipationSnapshot,
  BuildIntegrationLifecycleParticipationInput,
} from "./lifecycle";
export {
  ACTIVE_INTEGRATION_LIFECYCLE_STATES,
  INTEGRATION_LIFECYCLE_STATES,
  TERMINAL_INTEGRATION_LIFECYCLE_STATES,
  DefaultLifecycleParticipant,
  IntegrationAdapterLifecycleService,
  buildIntegrationLifecycleParticipation,
  canAcceptIntegrationRequests,
  canTransitionIntegrationLifecycle,
  createDefaultLifecycleParticipant,
  getAllowedIntegrationLifecycleTransitions,
  isActiveIntegrationLifecycleState,
  isIntegrationLifecycleState,
  isTerminalIntegrationLifecycleState,
  mapHealthStatusToParticipationReadiness,
  mapLifecycleStateToRecoveryStatus,
  mapLifecycleStateToShutdownStatus,
  toPlatformCapabilityParticipation,
} from "./lifecycle";
export type {
  DefaultLifecycleParticipantOptions,
  IntegrationLifecycleTransitionInput,
} from "./lifecycle";

export type { IntegrationOperationsStack, CreateIntegrationOperationsStackInput } from "./operations-stack";
export { createIntegrationOperationsStack } from "./operations-stack";

export type {
  ErrorTranslationContext,
  ErrorTranslator,
  IntegrationErrorSeverity,
  TranslatedIntegrationError,
  VendorErrorDiagnostics,
  VendorErrorInput,
  VendorErrorMapper,
} from "./errors/translation";
export {
  DefaultErrorTranslator,
  createDefaultErrorTranslator,
  buildDefaultTranslatedError,
  normalizeUnknownError,
  resolveErrorSeverity,
  shouldTripCircuitBreaker,
} from "./errors/translation";
export type { DefaultErrorTranslatorOptions } from "./errors/translation";

export type {
  CircuitBreaker,
  CircuitBreakerAvailabilityStatus,
  CircuitBreakerDiagnostics,
  CircuitBreakerState,
  RetryPolicy,
  RetryPolicyOptions,
  RetryDecision,
} from "./resilience";
export {
  DefaultCircuitBreaker,
  buildCircuitBreakerHealthMessage,
  createDefaultCircuitBreaker,
  DefaultRetryPolicy,
  createDefaultRetryPolicy,
} from "./resilience";

export type {
  Counter,
  Gauge,
  Histogram,
  HistogramSnapshot,
  IntegrationMetrics,
  IntegrationMetricsSummary,
  MetricLabels,
  MetricsProvider,
  RequestMetricOptions,
  Timer,
  TimerHandle,
  ErrorSummaryTracker,
} from "./observability/metrics";
export {
  DefaultIntegrationMetrics,
  InMemoryErrorSummaryTracker,
  InMemoryMetricsProvider,
  NoopMetricsProvider,
  STANDARD_INTEGRATION_METRIC_NAMES,
  createDefaultIntegrationMetrics,
  createInMemoryErrorSummaryTracker,
  createInMemoryMetricsProvider,
  createNoopMetricsProvider,
} from "./observability/metrics";

export type {
  IntegrationLogEntry,
  IntegrationLogFields,
  IntegrationLogLevel,
  IntegrationLogger,
} from "./observability/logging";
export {
  DefaultIntegrationLogger,
  NoopIntegrationLogger,
  buildErrorLogFields,
  createDefaultIntegrationLogger,
  createNoopIntegrationLogger,
} from "./observability/logging";

export type { IntegrationError, IntegrationErrorCategory } from "./errors";
export {
  IntegrationSdkError,
  createIntegrationError,
  createNotImplementedIntegrationError,
  isIntegrationError,
  isIntegrationErrorCategory,
} from "./errors";
export type { CreateIntegrationErrorInput } from "./errors";

export type {
  AuthCredentialReference,
  AuthenticateInput,
  AuthenticationDiagnostics,
  AuthenticationMode,
  AuthenticationProvider,
  AuthenticationResult,
  CredentialResolver,
  CredentialSourceType,
  ResolvedCredential,
  SecretProvider,
} from "./auth";
export {
  AUTHENTICATION_MODES,
  DefaultAuthenticationProvider,
  DefaultCredentialResolver,
  IMPLEMENTED_AUTHENTICATION_MODES,
  InMemorySecretProvider,
  PlaceholderVaultSecretProvider,
  buildAuthenticationDiagnostics,
  containsLikelySecret,
  createResolvedCredentialPreview,
  isAuthenticationMode,
  isImplementedAuthenticationMode,
  maskSecretValue,
  systemClock,
} from "./auth";

export type {
  ConnectionDefinition,
  ConnectionDiagnostics,
  ConnectionLifecycleState,
  ConnectionManager,
  ConnectionRecord,
  ConnectionRegistry,
  ConnectionRegistrySnapshot,
} from "./connection";
export {
  CONNECTION_LIFECYCLE_STATES,
  ConnectionLifecycleService,
  DefaultConnectionManager,
  InMemoryConnectionRegistry,
  buildConnectionDiagnostics,
  buildConnectionRecordDiagnostics,
  canTransitionConnectionLifecycle,
  createConnectionManager,
  getAllowedConnectionLifecycleTransitions,
  isActiveConnectionLifecycleState,
  validateConnectionDefinition,
} from "./connection";

export type { SdkResult } from "./errors";
export {
  authenticationFailedError,
  connectionNotFoundError,
  duplicateConnectionError,
  invalidIntegrationLifecycleTransitionError,
  sdkErr,
  sdkOk,
} from "./errors";

export type {
  MappingProfile,
  MappingDirection,
  EnumUnknownPolicy,
  MappingContext,
  MappingCapabilities,
  MappingResult,
  MappingError,
  FieldMapEntry,
  MappingDefinition,
  MappingProvider,
  MappingRegistryRegisterOptions,
  MappingDiagnostics,
  MappingProviderDiagnostics,
  MappingMetricsSnapshot,
  MappingMetrics,
  MappingPipelineExecuteInput,
  ValueTransformerKind,
  ValueTransformer,
  EnumMapperOptions,
  IdentityMapperOptions,
  RelationshipMapping,
  CollectionMappingOptions,
  NestedMappingOptions,
  MappingRegistry,
  MappingRegistryOptions,
  MappingPipeline,
  MappingPipelineOptions,
  IdentityMapper,
  EnumMapper,
  FieldMapper,
  FieldMapperOptions,
  RelationshipMapper,
  CollectionMapper,
  NestedMapper,
  MappingDefinitionValidationResult,
  CreateMappingProviderInput,
  MockMappingProviderOptions,
  MappingErrorContext,
} from "./mapping";
export {
  createMappingError,
  mappingValidationError,
  mappingProviderNotFoundError,
  mappingDefinitionNotFoundError,
  mappingDuplicateProviderError,
  mappingEnumUnknownError,
  mappingExecutionError,
  mappingErrorToIntegrationError,
  mapUnknownToMappingError,
  isMappingError,
  toProvisionalId,
  extractNativeId,
  hasProvisionalIdFormat,
  createIdentityMapper,
  PlaneIdentityMapper,
  ZammadIdentityMapper,
  createDateTransformer,
  createUuidTransformer,
  createBooleanTransformer,
  createNumberTransformer,
  createStringTransformer,
  createNullableTransformer,
  createArrayTransformer,
  createCustomTransformer,
  createEnumValueTransformer,
  ValueTransformerRegistry,
  createDefaultValueTransformerRegistry,
  createEnumMapper,
  createBidirectionalEnumMapper,
  createFieldMapper,
  createRelationshipMapper,
  createCollectionMapper,
  createNestedMapper,
  executeNestedDefinition,
  validateMappingDefinition,
  assertValidMappingDefinition,
  validateMappingProvider,
  definitionKey,
  validationResultToError,
  InMemoryMappingRegistry,
  createMappingRegistry,
  DefaultMappingMetrics,
  createMappingMetrics,
  STANDARD_MAPPING_METRIC_NAMES,
  DefaultMappingPipeline,
  createMappingPipeline,
  createMappingProvider,
  createDefinition,
  createMockMappingProvider,
  MOCK_MAPPING_FIXTURES,
} from "./mapping";

export type {
  DeliveryMechanism,
  EventIdentitySource,
  IntegrationSourceEvent,
  BuildIntegrationSourceEventInput,
  DerivedEventIdentity,
  DeriveSourceEventIdInput,
  SchemaCompatibility,
  SchemaCompatibilityResult,
  SchemaVersion,
  EventError,
  EventErrorCategory,
  EventErrorContext,
  EventDeduplicationStore,
  EventDiagnosticsCollector,
  EventDiagnosticsSnapshot,
  EventMetrics,
  EventMetricsSnapshot,
  EventCapabilityDeclaration,
  EventCapabilityId,
  WebhookCapabilityDeclaration,
  PollingCapabilityDeclaration,
  IntegrationEventEnvelopeCompat,
  FromIntegrationEventEnvelopeMeta,
  WebhookManager,
  WebhookDefinition,
  WebhookManagerOperation,
  WebhookRegistrationRequest,
  WebhookUpdateRequest,
  WebhookRegistrationResult,
  WebhookValidationOutcome,
  WebhookVerifier,
  WebhookVerificationRequest,
  WebhookVerificationResult,
  ReplayProtection,
  ReplayStore,
  ReplayDecision,
  ReplayCheckResult,
  WebhookProcessingPipeline,
  WebhookProcessingResult,
  WebhookProcessingOutcome,
  WebhookDecoder,
  WebhookTranslator,
  PollingSource,
  PollingSourceDefinition,
  PollingMode,
  PollingCursor,
  PollingCursorKind,
  PollingCheckpoint,
  PollingCheckpointStore,
  PollingExecutionPipeline,
  PollingExecutionResult,
  PollingExecutionOutcome,
  PollingRunOptions,
  LegacySyncCursor,
  LegacySyncServiceLike,
  LegacyWebhookServiceLike,
  AsWebhookManagerOptions,
} from "./events";
export {
  DELIVERY_MECHANISMS,
  EVENT_IDENTITY_SOURCES,
  SOURCE_EVENT_ENVELOPE_SCHEMA_VERSION,
  SOURCE_EVENT_PAYLOAD_SCHEMA_VERSION,
  isDeliveryMechanism,
  buildIntegrationSourceEvent,
  createSdkEventId,
  deriveDeduplicationKey,
  deriveSourceEventId,
  fingerprintPayload,
  assertEnvelopeSchemaCompatible,
  assertPayloadSchemaCompatible,
  compareSchemaVersions,
  currentEnvelopeSchemaVersion,
  currentPayloadSchemaVersion,
  parseSchemaVersion,
  createEventError,
  eventDuplicateError,
  eventErrorToIntegrationError,
  eventValidationError,
  isEventError,
  mapEventErrorCategory,
  pollingCancelledError,
  pollingCheckpointError,
  pollingLimitExceededError,
  pollingStallDetectedError,
  schemaIncompatibleError,
  unsupportedWebhookOperationError,
  webhookReplayRejectedError,
  webhookVerificationFailedError,
  InMemoryEventDeduplicationStore,
  createInMemoryEventDeduplicationStore,
  DefaultEventDiagnosticsCollector,
  buildSafeEventLogFields,
  createEventDiagnosticsCollector,
  DefaultEventMetrics,
  STANDARD_EVENT_METRIC_NAMES,
  createEventMetrics,
  EVENT_CAPABILITY_IDS,
  declareEventCapabilities,
  declarePollingCapability,
  declareWebhookCapability,
  listKnownEventCapabilityIds,
  resolveRegisteredEventCapabilityIds,
  fromIntegrationEventEnvelope,
  toIntegrationEventEnvelope,
  WEBHOOK_MANAGER_OPERATIONS,
  asWebhookManager,
  validateWebhookEndpoint,
  createWebhookEndpoint,
  isHttpsCallbackUrl,
  computeMockHmacSignature,
  createMockHmacWebhookVerifier,
  DefaultReplayProtection,
  InMemoryReplayStore,
  createInMemoryReplayStore,
  createReplayProtection,
  DefaultWebhookProcessingPipeline,
  createWebhookProcessingPipeline,
  POLLING_MODES,
  POLLING_CURSOR_KINDS,
  isPollingMode,
  createOpaqueCursor,
  createTimestampCursor,
  createOffsetCursor,
  createPageCursor,
  createCompositeCursor,
  createProviderCursor,
  fromSyncCursor,
  toSyncCursor,
  cursorsEqual,
  InMemoryPollingCheckpointStore,
  createInMemoryPollingCheckpointStore,
  createPollingSourceFromSync,
  wrapSyncCursorAsPollingCursor,
  unwrapPollingCursorAsSyncCursor,
  DefaultPollingExecutionPipeline,
  createPollingExecutionPipeline,
  createMockEventTestHarness,
  createMockJsonWebhookDecoder,
  createMockPollingSource,
  createMockSourceEvent,
  createMockWebhookTranslator,
} from "./events";

// --- Adapter Development Harness & Certification (OSS-100-09) ---
export type {
  HarnessCheckOutcome,
  HarnessCheckResult,
  HarnessCategoryResult,
  AdapterPackageStructure,
  AdapterHarnessOptions,
  AdapterHarnessState,
  ScaffoldAdapterInput,
  AdapterFixtureSet,
  AdapterFileMap,
  AdapterTemplate,
  AdapterTemplateFileSpec,
  AdapterScaffoldResult,
  CertificationCategory,
  CertificationCategoryInput,
  AdapterCertificationSubject,
  AdapterCertificationReport,
  AdapterComplianceInput,
  AdapterComplianceResult,
  AdapterValidatorInput,
  AdapterValidatorResult,
  CapabilityValidationInput,
  ContractArea,
  ContractSubjectMetadata,
  AdapterContractSuiteResult,
  BuildRequestContextInput,
  FixtureFramework,
  AdapterMockHarnessOptions,
  SimulatedHttpResult,
  DocumentationGeneratorInput,
  QualityGateStatus,
  AdapterQualityInputs,
  AdapterQualityReport,
  CompatibilityClassification,
  CompatibilityFeature,
  AdapterCompatibilityInput,
  AdapterCompatibilityResult,
  PerformanceTiming,
  AdapterPerformanceReport,
  AdapterPerformanceHarnessOptions,
  BoundaryValidationInput,
  BoundaryValidationResult,
  CiCheckBundle,
} from "./harness";
export {
  AdapterHarness,
  createAdapterHarness,
  mergeFileMaps,
  REFERENCE_ADAPTER_TEMPLATE,
  getAdapterTemplate,
  listRequiredTemplatePaths,
  AdapterScaffold,
  scaffoldAdapter,
  createAdapterScaffold,
  CERTIFICATION_CATEGORIES,
  AdapterCertification,
  createAdapterCertification,
  certifyAdapter,
  summariseOutcome,
  buildCertificationReport,
  certificationReportToMarkdown,
  AdapterCompliance,
  createAdapterCompliance,
  assessAdapterCompliance,
  AdapterValidator,
  createAdapterValidator,
  validateAdapter,
  validateAdapterCapabilities,
  AdapterContractSuite,
  createAdapterContractSuite,
  runAdapterContractSuite,
  AdapterTestKit,
  createAdapterTestKit,
  createDefaultFixtures,
  createFixtureFramework,
  AdapterMockHarness,
  createAdapterMockHarness,
  AdapterDocumentationGenerator,
  createAdapterDocumentationGenerator,
  AdapterQualityReportBuilder,
  buildAdapterQualityReport,
  createAdapterQualityReportBuilder,
  AdapterCompatibilitySuite,
  createAdapterCompatibilitySuite,
  evaluateAdapterCompatibility,
  AdapterPerformanceHarness,
  createAdapterPerformanceHarness,
  AdapterBoundaryValidator,
  createAdapterBoundaryValidator,
  validateAdapterBoundary,
  DEFAULT_FORBIDDEN_IMPORT_PATTERNS,
  DEFAULT_PROVIDER_LEAK_PATTERNS,
  runCertificationChecks,
  runContractChecks,
  runBoundaryChecks,
  runDocumentationChecks,
  buildQualityReport,
} from "./harness";
