export {
  createEngineeringIntelligenceServices,
  createEngineeringAggregationService,
  createQualityScoringService,
  createEngineeringHealthService,
  createTrendEngineService,
  createBenchmarkService,
  createBaselineService,
  createHistoricalSnapshotService,
  createEngineeringRiskService,
  createEngineeringIntelligenceService,
  computeQualityScore,
  computeTrendDirection,
  computeTrendDelta,
  rollingAverage,
  healthStatusFromScore,
  riskLevelFromScore,
  aggregateRisk,
  normalizeWeights,
  clamp01to100,
  invertPenalty,
  type EngineeringIntelligenceServices,
  type EngineeringIntelligenceServiceDeps,
} from "./factory";
