/** Accessor coverage (APZMETRICS-003). */
import { afterEach, describe, expect, it } from "vitest";

import * as api from "./metrics-api";
import { createMockMetricsClient } from "./mock-metrics-client";

afterEach(() => {
  api.resetMetricsClient();
});

describe("metrics-api coverage", () => {
  it("delegates all facet accessors to the active client", async () => {
    api.setMetricsClient(createMockMetricsClient());
    const calls = [
      api.listMetrics(),
      api.getMetric("id"),
      api.createMetric({ key: "k", name: "n", status: "active" }),
      api.updateMetric("id", { name: "n2" }),
      api.listDefinitions(),
      api.getDefinition("id"),
      api.createDefinition({
        metricId: "m",
        key: "k",
        name: "n",
        kind: "gauge",
        versionNumber: 1,
        status: "active",
      }),
      api.updateDefinition("id", { name: "n2" }),
      api.listVersions(),
      api.getVersion("id"),
      api.createVersion({ metricId: "m", versionNumber: 1, status: "active" }),
      api.updateVersion("id", { status: "inactive" }),
      api.listCategories(),
      api.getCategory("id"),
      api.createCategory({ key: "k", name: "n", status: "active" }),
      api.updateCategory("id", { name: "n2" }),
      api.listGroups(),
      api.getGroup("id"),
      api.createGroup({ key: "k", name: "n", status: "active" }),
      api.updateGroup("id", { name: "n2" }),
      api.listDimensions(),
      api.getDimension("id"),
      api.createDimension({
        key: "k",
        name: "n",
        dataType: "string",
        status: "active",
      }),
      api.updateDimension("id", { name: "n2" }),
      api.listLabels(),
      api.getLabel("id"),
      api.createLabel({ key: "k", name: "n", status: "active" }),
      api.updateLabel("id", { name: "n2" }),
      api.listUnits(),
      api.getUnit("id"),
      api.createUnit({ key: "k", name: "n", status: "active" }),
      api.updateUnit("id", { name: "n2" }),
      api.listFormulas(),
      api.getFormula("id"),
      api.createFormula({ expression: "a+b", language: "expression", status: "draft" }),
      api.updateFormula("id", { expression: "a" }),
      api.listAggregations(),
      api.getAggregation("id"),
      api.createAggregation({ key: "k", name: "n", method: "avg", status: "active" }),
      api.updateAggregation("id", { name: "n2" }),
      api.listThresholds(),
      api.getThreshold("id"),
      api.createThreshold({
        metricId: "m",
        name: "n",
        operator: "gt",
        valueLabel: "1",
        severity: "info",
        status: "active",
      }),
      api.updateThreshold("id", { name: "n2" }),
      api.listOwners(),
      api.getOwner("id"),
      api.createOwner({
        metricId: "m",
        ownerType: "team",
        ownerRef: "t",
        status: "active",
      }),
      api.updateOwner("id", { ownerRef: "t2" }),
      api.listConsumers(),
      api.getConsumer("id"),
      api.createConsumer({
        metricId: "m",
        consumerType: "module",
        consumerRef: "c",
        status: "active",
      }),
      api.updateConsumer("id", { consumerRef: "c2" }),
      api.listRetentionPolicies(),
      api.getRetentionPolicy("id"),
      api.createRetentionPolicy({
        key: "k",
        name: "n",
        retentionDays: 30,
        status: "active",
      }),
      api.updateRetentionPolicy("id", { retentionDays: 60 }),
      api.listClassifications(),
      api.getClassification("id"),
      api.createClassification({
        key: "k",
        name: "n",
        level: "operational",
        status: "active",
      }),
      api.updateClassification("id", { name: "n2" }),
      api.listDependencies(),
      api.getDependency("id"),
      api.createDependency({
        metricId: "m1",
        dependsOnMetricId: "m2",
        dependencyKind: "uses",
        status: "active",
      }),
      api.updateDependency("id", { status: "inactive" }),
      api.listKPIs(),
      api.getKPI("id"),
      api.createKPI({ key: "k", name: "n", metricId: "m", status: "active" }),
      api.updateKPI("id", { name: "n2" }),
      api.listKPIGroups(),
      api.getKPIGroup("id"),
      api.createKPIGroup({ key: "k", name: "n", status: "active" }),
      api.updateKPIGroup("id", { name: "n2" }),
      api.listKPITargets(),
      api.getKPITarget("id"),
      api.createKPITarget({
        kpiId: "k",
        periodLabel: "p",
        targetValueLabel: "1",
        status: "active",
      }),
      api.updateKPITarget("id", { periodLabel: "p2" }),
      api.listRelationships(),
      api.getRelationship("id"),
      api.createRelationship({
        fromMetricId: "m1",
        toMetricId: "m2",
        relationshipKind: "correlates_with",
        status: "active",
      }),
      api.updateRelationship("id", { status: "inactive" }),
      api.listMetadata(),
      api.getMetadata("id"),
      api.createMetadata({
        subjectKind: "metric",
        subjectId: "m",
        key: "k",
        status: "active",
      }),
      api.updateMetadata("id", { valueLabel: "v" }),
      api.getMetricsDiagnostics(),
      api.getMetricsHealth(),
      api.getMetricsReadiness(),
      api.getMetricsCapabilities(),
    ];
    const results = await Promise.all(calls);
    expect(results.length).toBeGreaterThan(80);
  });
});
