/** Ensure every query-key factory is exercised. */
import { describe, expect, it } from "vitest";
import { QueryClient } from "@tanstack/react-query";
import { clearMetricsQueries, metricsQueryKeys } from "./query-keys";

describe("metricsQueryKeys full surface", () => {
  it("invokes every list/detail factory", () => {
    const keys = [
      metricsQueryKeys.all,
      metricsQueryKeys.metrics.all,
      metricsQueryKeys.metrics.list(),
      metricsQueryKeys.metrics.detail("1"),
      metricsQueryKeys.definitions.all,
      metricsQueryKeys.definitions.list(),
      metricsQueryKeys.definitions.detail("1"),
      metricsQueryKeys.versions.all,
      metricsQueryKeys.versions.list(),
      metricsQueryKeys.versions.detail("1"),
      metricsQueryKeys.categories.all,
      metricsQueryKeys.categories.list(),
      metricsQueryKeys.categories.detail("1"),
      metricsQueryKeys.groups.all,
      metricsQueryKeys.groups.list(),
      metricsQueryKeys.groups.detail("1"),
      metricsQueryKeys.dimensions.all,
      metricsQueryKeys.dimensions.list(),
      metricsQueryKeys.dimensions.detail("1"),
      metricsQueryKeys.labels.all,
      metricsQueryKeys.labels.list(),
      metricsQueryKeys.labels.detail("1"),
      metricsQueryKeys.units.all,
      metricsQueryKeys.units.list(),
      metricsQueryKeys.units.detail("1"),
      metricsQueryKeys.formulas.all,
      metricsQueryKeys.formulas.list(),
      metricsQueryKeys.formulas.detail("1"),
      metricsQueryKeys.aggregations.all,
      metricsQueryKeys.aggregations.list(),
      metricsQueryKeys.aggregations.detail("1"),
      metricsQueryKeys.thresholds.all,
      metricsQueryKeys.thresholds.list(),
      metricsQueryKeys.thresholds.detail("1"),
      metricsQueryKeys.owners.all,
      metricsQueryKeys.owners.list(),
      metricsQueryKeys.owners.detail("1"),
      metricsQueryKeys.consumers.all,
      metricsQueryKeys.consumers.list(),
      metricsQueryKeys.consumers.detail("1"),
      metricsQueryKeys.retentionPolicies.all,
      metricsQueryKeys.retentionPolicies.list(),
      metricsQueryKeys.retentionPolicies.detail("1"),
      metricsQueryKeys.classifications.all,
      metricsQueryKeys.classifications.list(),
      metricsQueryKeys.classifications.detail("1"),
      metricsQueryKeys.dependencies.all,
      metricsQueryKeys.dependencies.list(),
      metricsQueryKeys.dependencies.detail("1"),
      metricsQueryKeys.kpis.all,
      metricsQueryKeys.kpis.list(),
      metricsQueryKeys.kpis.detail("1"),
      metricsQueryKeys.kpiGroups.all,
      metricsQueryKeys.kpiGroups.list(),
      metricsQueryKeys.kpiGroups.detail("1"),
      metricsQueryKeys.kpiTargets.all,
      metricsQueryKeys.kpiTargets.list(),
      metricsQueryKeys.kpiTargets.detail("1"),
      metricsQueryKeys.relationships.all,
      metricsQueryKeys.relationships.list(),
      metricsQueryKeys.relationships.detail("1"),
      metricsQueryKeys.metadata.all,
      metricsQueryKeys.metadata.list(),
      metricsQueryKeys.metadata.detail("1"),
      metricsQueryKeys.diagnostics.all,
      metricsQueryKeys.diagnostics.health(),
      metricsQueryKeys.diagnostics.readiness(),
      metricsQueryKeys.diagnostics.capabilities(),
      metricsQueryKeys.diagnostics.management(),
      metricsQueryKeys.health(),
      metricsQueryKeys.readiness(),
      metricsQueryKeys.capabilities(),
    ];
    expect(keys.length).toBeGreaterThan(60);
    clearMetricsQueries(new QueryClient());
  });
});
