export type { RepositoryContext, PersistenceMeta, AggregateKind } from "./types";

export {
  PersistenceError,
  notFoundError,
  revisionConflictError,
  tenantMismatchError,
  unauthorizedError,
  validationError,
  type PersistenceErrorCode,
} from "./errors";

export {
  OPERATION_PERMISSION_MAP,
  assertPermission,
  hasAnyMatchingPermission,
  permissionsForOperation,
  type RepositoryOperation,
} from "./authorization/testing-authorization";

export {
  TESTING_PERMISSION_SEED_KEYS,
  listTestingPermissionSeedKeys,
  seedTestingPermissions,
  type PermissionRegistrationTarget,
  type TestingPermissionSeedKey,
} from "./authorization/permission-seed";

export {
  assertTenantOwnership,
  assertOrganisationFilter,
  assertRevisionMatch,
  assertRequiredString,
  assertNonNegativeInteger,
  assertEnumValue,
  validatePriority,
  validateRiskLevel,
  validateTestStatus,
  validateExecutionStatus,
  validateExecutionType,
  validateEvidenceType,
  validateEvidenceLifecycleStatus,
  validateCertificationStatus,
  validateCertificationGateOutcome,
  validateApprovalStatus,
  validateReleaseReadinessStatus,
  validateReleaseGovernanceStatus,
  validateReleaseScopeKind,
  validateReleaseApprovalStageKind,
  validateReleaseApprovalStatus,
  validateReleaseDecisionVerdict,
  validateCoverageKind,
  validateDefectProviderKind,
  validateDefectStatus,
  validateAutomationType,
  validateAutomationAdapterKind,
  validateAutomationImportStatus,
  validateNormalizedResultStatus,
  validateTraceabilityType,
  validateWorkItemKind,
  validateLikelihood,
  validateImpact,
  validateBusinessCriticality,
  validateRegressionImportance,
  validateCaseVersionReason,
  validateSeverity,
  validateTestResultStatus,
  validateExecutionApprovalState,
} from "./validation/persistence-validation";

export const TESTING_PERSISTENCE_VERSION = "0.11.0";

export type * from "./repositories/records";
export type * from "./repositories/interfaces";
export type {
  ListQuery,
  PageResult,
  SortDirection,
  SortSpec,
} from "./repositories/types";
export {
  normalizeListQuery,
  paginateItems,
  compareValues,
  matchesSearch,
  matchesFilters,
} from "./repositories/types";

export {
  createInMemoryTestingPersistence,
  createEmptyInMemoryStores,
  type InMemoryStores,
} from "./repositories/in-memory/factory";

export { createPostgresTestingPersistence } from "./repositories/postgres/factory";

export {
  metaFromRow,
  requirementToRow,
  rowToRequirement,
  workItemToRow,
  rowToWorkItem,
  riskToRow,
  rowToRisk,
  testPlanToRow,
  rowToTestPlan,
  testSuiteToRow,
  rowToTestSuite,
  testCaseToRow,
  rowToTestCase,
  testStepToRow,
  rowToTestStep,
  testCaseVersionToRow,
  rowToTestCaseVersion,
  testPlanVersionToRow,
  rowToTestPlanVersion,
  testSuiteVersionToRow,
  rowToTestSuiteVersion,
  regressionSetToRow,
  rowToRegressionSet,
  executionSessionToRow,
  rowToExecutionSession,
  manualExecutionToRow,
  rowToManualExecution,
  evidenceToRow,
  rowToEvidence,
  approvalToRow,
  rowToApproval,
  approvalHistoryToRow,
  rowToApprovalHistory,
  certificationToRow,
  rowToCertification,
  certificationGateDefinitionToRow,
  rowToCertificationGateDefinition,
  certificationGateEvaluationToRow,
  rowToCertificationGateEvaluation,
  certificationRuleToRow,
  rowToCertificationRule,
  certificationAuditToRow,
  rowToCertificationAudit,
  certificationHistoryToRow,
  rowToCertificationHistory,
  releaseReadinessToRow,
  rowToReleaseReadiness,
  releaseToRow,
  rowToRelease,
  releaseScopeToRow,
  rowToReleaseScope,
  releasePackageToRow,
  rowToReleasePackage,
  releaseCandidateToRow,
  rowToReleaseCandidate,
  releaseApprovalToRow,
  rowToReleaseApproval,
  releaseDecisionToRow,
  rowToReleaseDecision,
  releaseEvidenceToRow,
  rowToReleaseEvidence,
  releaseDependencyToRow,
  rowToReleaseDependency,
  releaseNoteToRow,
  rowToReleaseNote,
  releaseRiskAssessmentToRow,
  rowToReleaseRiskAssessment,
  releaseReadinessSnapshotToRow,
  rowToReleaseReadinessSnapshot,
  releaseSummarySnapshotToRow,
  rowToReleaseSummarySnapshot,
  releaseAuditToRow,
  rowToReleaseAudit,
  coverageToRow,
  rowToCoverage,
  defectLinkToRow,
  rowToDefectLink,
  qualitySnapshotToRow,
  rowToQualitySnapshot,
  regressionAnalysisToRow,
  rowToRegressionAnalysis,
  automationDefinitionToRow,
  rowToAutomationDefinition,
  traceabilityLinkToRow,
  rowToTraceabilityLink,
  configurationToRow,
  rowToConfiguration,
  registryEntryToRow,
  rowToRegistryEntry,
  executionHistoryToRow,
  rowToExecutionHistory,
  auditToRow,
  rowToAudit,
  isoFromDate,
  dateFromIso,
} from "./repositories/mappers/row-mappers";
