export {
  assertNonEmpty,
  assertValidTestStatus,
  assertValidPriority,
  assertValidTestResultStatus,
  assertValidLikelihood,
  assertValidCaseVersionReason,
  assertValidExecutionApprovalState,
  assertTraceabilityKinds,
  assertNoSelfLink,
  assertApprovalDecisionAllowed,
  assertOwnershipId,
  assertVersionBump,
  isKnownTraceabilityKind,
} from "./domain-validation";
