/**
 * Cap A–F permission catalogue and roles — APZQEP-152.
 * Least privilege: tenant-member does NOT receive these by default.
 */

export const DEFAULT_QEP_OPERATOR_ROLE_ID = "role-qep-operator";
export const DEFAULT_QEP_READER_ROLE_ID = "role-qep-reader";

/** Authoritative Cap A–F permission keys used by domain services. */
export const QEP_CORE_QE_PERMISSIONS = [
  "qep.home.read",
  "qep.search.read",
  "qep.release_readiness.read",
  "qep.integrations.read",
  "qep.quality_flows.read",
  "qep.quality_flows.operate",
  "qep.certification.read",
  "qep.certification.decide",
  "qep.automation.read",
  "qep.automation.operate",
  "qep.scm.read",
  "qep.scm.operate",
  "qep.portfolio.read",
  "qep.portfolio.operate",
  "qep.qi.read",
  "qep.qi.operate",
  "qep.ai_workspace.read",
  "qep.ai_workspace.operate",
  "qep.dashboards.read",
  "qep.suites.read",
  "qep.suites.create",
  "qep.suites.update",
  "qep.suites.lifecycle",
  "qep.suites.admin",
  "qep.execution_plans.read",
  "qep.execution_plans.create",
  "qep.execution_plans.update",
  "qep.execution_plans.lifecycle",
  "qep.execution_plans.handoff",
  "qep.execution_plans.admin",
  "qep.execution_workspace.read",
  "qep.execution_workspace.create",
  "qep.execution_workspace.execute",
  "qep.execution_workspace.lifecycle",
  "qep.execution_workspace.amend",
  "qep.execution_workspace.admin",
  "qep.defects.read",
  "qep.defects.create",
  "qep.defects.update",
  "qep.defects.lifecycle",
  "qep.defects.admin",
  "qep.enterprise_requirements.read",
  "qep.enterprise_requirements.create",
  "qep.enterprise_requirements.update",
  "qep.enterprise_requirements.lifecycle",
  "qep.enterprise_requirements.admin",
  "qep.enterprise_reporting.read",
  "qep.enterprise_reporting.create",
  "qep.enterprise_reporting.update",
  "qep.enterprise_reporting.admin",
  "qep.specification.read",
  "qep.specification.create",
  "qep.specification.update",
  "qep.specification.search",
  "qep.traceability.trace_links.view",
  "qep.traceability.trace_links.create",
  "qep.*",
] as const;

export const QEP_OPERATOR_PERMISSIONS = [
  "qep.home.read",
  "qep.search.read",
  "qep.release_readiness.read",
  "qep.integrations.read",
  "qep.quality_flows.read",
  "qep.quality_flows.operate",
  "qep.certification.read",
  "qep.certification.decide",
  "qep.automation.read",
  "qep.automation.operate",
  "qep.scm.read",
  "qep.scm.operate",
  "qep.portfolio.read",
  "qep.portfolio.operate",
  "qep.qi.read",
  "qep.qi.operate",
  "qep.ai_workspace.read",
  "qep.ai_workspace.operate",
  "qep.dashboards.read",
  "qep.suites.read",
  "qep.suites.create",
  "qep.suites.update",
  "qep.suites.lifecycle",
  "qep.execution_plans.read",
  "qep.execution_plans.create",
  "qep.execution_plans.update",
  "qep.execution_plans.lifecycle",
  "qep.execution_plans.handoff",
  "qep.execution_workspace.read",
  "qep.execution_workspace.create",
  "qep.execution_workspace.execute",
  "qep.execution_workspace.lifecycle",
  "qep.execution_workspace.amend",
  "qep.defects.read",
  "qep.defects.create",
  "qep.defects.update",
  "qep.defects.lifecycle",
  "qep.enterprise_requirements.read",
  "qep.enterprise_requirements.create",
  "qep.enterprise_requirements.update",
  "qep.enterprise_requirements.lifecycle",
  "qep.enterprise_reporting.read",
  "qep.enterprise_reporting.create",
  "qep.enterprise_reporting.update",
  "qep.specification.read",
  "qep.specification.create",
  "qep.specification.update",
  "qep.specification.search",
  "qep.traceability.trace_links.view",
  "qep.traceability.trace_links.create",
] as const;

export const QEP_READER_PERMISSIONS = [
  "qep.home.read",
  "qep.search.read",
  "qep.release_readiness.read",
  "qep.integrations.read",
  "qep.quality_flows.read",
  "qep.certification.read",
  "qep.automation.read",
  "qep.scm.read",
  "qep.portfolio.read",
  "qep.qi.read",
  "qep.ai_workspace.read",
  "qep.dashboards.read",
  "qep.suites.read",
  "qep.execution_plans.read",
  "qep.execution_workspace.read",
  "qep.defects.read",
  "qep.enterprise_requirements.read",
  "qep.enterprise_reporting.read",
  "qep.specification.read",
  "qep.specification.search",
  "qep.traceability.trace_links.view",
] as const;

/** When true, auto-provision also assigns qep-operator (dev/cert only). */
export function isQepOperatorAutoAssignEnabled(
  env: NodeJS.ProcessEnv = process.env,
): boolean {
  const raw = (env.APZQEP_QEP_AUTO_ASSIGN_OPERATOR ?? "").toLowerCase();
  return raw === "true" || raw === "1" || raw === "yes";
}
